### ISSUE TITLE
Support Git LFS

### ISSUE THREAD

**Issue by murphye** [openshift/source-to-image#1032]
Existing thread on LFS support:
https://www.mail-archive.com/users@lists.openshift.redhat.com/msg03205.html

I would like to see this added, if possible. I just ran into an issue where I had a machine learning model 102 MB in size, and had to use LFS to push to GitHub. I wanted to use S2I to build an application to deploy this model, but it's not currently possible due to S2I Git client not having LFS installed.

LFS is built into GitHub and the client now, so popularity is rising.

Thanks.

**Comment by bparees** [comment]
@murphye can you achieve your objective by manually cloning your repo and then use the `--copy` flag on s2i build?  (which causes s2i to copy the source from a local dir instead of cloning it)?

it's a bit more setup work but it should allow you to accomplish the same goal (Assuming you're using s2i on the cli.  if you're using it from within openshift, we can have a different conversation about solutions)

**Comment by murphye** [comment]
@bparees Yes, this is for OpenShift. Sorry to not specify.

Definitely interested in workarounds for this issue, but the fact remains that the only way to clone the entire repo is to have the LFS plugin installed in Git.

**Comment by murphye** [comment]
@bparees One option I have considered trying is to simply have a Jenkinsfile that clones the repo and just do an S2I binary build in that pipeline.

**Comment by bparees** [comment]
@murphye heh, yes i was just about to suggest binary builds as a way around this, which basically just defers the cloning problem to an external step.  So doing it as part of a jenkins pipeline could certainly work.
