### ISSUE TITLE
Can S2I be used on AWS?

### ISSUE THREAD

**Issue by dAnjou** [openshift/source-to-image#1058]
Pretty broad question, I know, but that's intentional.

This repo currently belongs to the OpenShift organization but the README mentions OpenShift only once, as an example platform that S2I could be used on. So, I'm wondering how agnostic S2I is? And how feasible is it to use it on other cloud platforms, specifically AWS?

In particular, I'm concerned about the fact that S2I spawns an actual container for `s2i build`. Pretty sure that can be done on those other platforms as well, but would I wanna do that? Or would that be a makeshift solution? (no pun intended)

I should add that I'm not too familiar with any of these platforms and maybe you could also explain how S2I is integrated in OpenShift and how exactly that works.

**Comment by bparees** [comment]
s2i is a fully standalone project that enables building application images by combining source code and an appropriate builder image.

OpenShift uses(wraps/embeds) this project to enable the build feature that openshift provides, but the project can be used standalone if you just want to build application images by invoking it directly.

There are really two ways you can use it standalone:

1) provided you have a docker daemon on your host, you can use s2i in "traditional" mode where it will use the docker daemon to spawn a container from the builder image, inject the source code into the container, invoke the app assembly logic, and then commit the new state of the container as your resulting application image.  This can work in any environment that has a docker daemon/docker socket available.  So you can definitely do it on AWS, specifically on an ec2 instance w/ docker available.

2) you can use s2i in generate mode, in which it will generate an opinionated dockerfile which, when built using the image building tool of your choice (e.g. docker, buildah, imagebuilder, kaniko, etc), will produce an application image.  The value of this approach over simply writing your own dockerfiles is the consistency of the dockerfiles and resulting application images, ability to leverage the ecosystem of s2i builder images, and more tight control over what commands are being run in the dockerfiles vs what you might get if every developer just wrote their own.

Of course if you want to use s2i via openshift, you can use it on any openshift cluster running on any environment (aws, azure, gcp, baremetal, vsphere, openstack, etc).

**Comment by dAnjou** [comment]
Thanks a lot for the hint regarding "generate mode", @bparees! It works very well for me.

**Comment by bparees** [comment]
Great!

**Comment by dAnjou** [comment]
@bparees, hope you can help me again with one more question. Maybe I'm missing something but do I even need S2I when I choose the Dockerfile approach? It seems I only need 2 Dockerfiles, maybe not even generated but handwritten, one for the builder image, one for the first app image and one for every incremental app image.

**Comment by bparees** [comment]
Need it?  no.  The intent is that s2i gives you strongly opinionated dockerfiles that leverage other images that know how to build applications from source for various languages/frameworks.

That means:
1) you don't have to go find your own php base image (for example)
2) figure out how to invoke the right build/config tools in that image to assemble your application and produce a runnable image
3) worry that everyone in the org does it slightly differently resulting in dockerfiles with different behavior/quality
4) have to learn dockerfile syntax at all

But if you're comfortable writing dockerfiles and are not worried about people doing "bad" (non-best-practice or insecure) things in their dockerfiles, then sure, s2i in "generate" mode doesn't add a ton of value.

Full disclosure, we added the s2i generate capability because openshift was pivoting away from docker as the container runtime, so we needed a way to make s2i continue to work within openshift, when docker was not present.  The resulting s2i generate feature allowed us to preserve the s2i build experience within openshift, even when there is no docker daemon present.  It wasn't explicitly built with the idea that direct s2i cli users would have a lot of use for it, but those who want to move away from docker as a runtime while still leveraging any s2i invesment they may have made, will find it useful.

**Comment by adambkaplan** [comment]
`s2i generate` also allows s2i to be used as a task step in a Tekton task or pipeline. See https://github.com/tektoncd/catalog/tree/master/task/s2i/0.1

**Comment by dAnjou** [comment]
@bparees Thanks again for all this info! I've presented S2I to my coworkers because I can totally see the benefits of building images with this pattern, let's see if they are willing to adopt it.
