### ISSUE TITLE
using assemble script on the runtime image during s2i build with --runtime-image instead of assemble-runtime script

### ISSUE THREAD

**Issue by rprakashg-redhat** [openshift/source-to-image#1096]
I was wondering why we need a separate assemble-runtime script when using s2i build with --runtime-image parameter. Run time image also has an assemble script shouldn't we just run that. With the way it currently works it seems like I have to duplicate that into assemble-runtime script when using s2i build with --runtime-image parameter.

Thoughts?

Thanks,
Ram

**Comment by bparees** [comment]
if you'd like it to be the same script, then symlink it, but in most cases assemble scripts require/expect compilation tooling that isn't expected to exist in a pure runtime image.  That's the whole point of separating them, so you don't have to carry that tooling in your runtime image.

I should also note that the assemble vs runtime image split concept was largely abandoned in s2i (we dropped support for it in openshift, which is the primary consumer of s2i), in part because of the complexity and in part because docker introduced multistage builds which alllow you to accomplish a similar result (compile the code in one layer, then just copy the binary to a new image with a different base)
