### ISSUE TITLE
Is it possible to use podman for s2i build?

### ISSUE THREAD

**Issue by mrshimi17** [openshift/source-to-image#1119]

**Comment by bparees** [comment]
you can use the `--as-dockerfile` argument to generate a dockerfile that you can then use with podman to build the image(instead of allowing s2i to invoke docker to build the image), but s2i doesn't have direct integration to invoke podman for the build itself.

**Comment by mrshimi17** [comment]
Thanks @bparees That works.

But I see the generated image(using podman) size is double the image size generated by docker.  (Using the same base image)

Do you know the reason why?

**Comment by bparees** [comment]
It may have to do with the way s2i only adds a single layer to the image when doing a direct build, while building from a generated docker file introduces more layers.

If you build the generated docker file with docker instead of podman, do you see the same doubled image size?

Can you paste the generated docker file?
