### ISSUE TITLE
ERROR: --runtime-image cannot be used with --as-dockerfile

### ISSUE THREAD

**Issue by jmtd** [openshift/source-to-image#1126]
It would be good for this limitation to be addressed.

This is a fairly significant limitation. `--as-dockerfile` is required to function correctly with an engine other than Docker (even with Docker API emulation, there can be strange problems with Podman), so this effectively restricts the runtime workflow to Docker.

**Comment by bparees** [comment]
the --runtime-image feature was mostly implemented to support creating lightweight runtime-only application images in openshift before docker supported multistage builds (which allow you to accomplish the same thing, more or less).

in fact the feature ended up getting deprecated out of openshift if i recall correctly, or perhaps never made it in...in any case it was considered a bit of a dead end once docker introduced multistage builds so it's unlikely that s2i will be extended to implement the runtime-image functionality for the dockerfile generation mode.

**Comment by jmtd** [comment]
Thanks for your reply @bparees !

> the --runtime-image feature was mostly implemented to support creating lightweight runtime-only application images in openshift before docker supported multistage builds (which allow you to accomplish the same thing, more or less).

In the context of OCP, is this effectively a multi-stage build, with a source-to-image build (=SourceBuildStrategy?) triggering a second-stage Dockerfile-based build? (Or I suppose one Dockerfile-based multi-stage build doing all the work in one go... although re-implementing all the short-cuts from S2I in a multi-stage Dockerfile sounds a little painful to me)

> in fact the feature ended up getting deprecated out of openshift if i recall correctly, or perhaps never made it in...in any case it was considered a bit of a dead end once docker introduced multistage builds

That's very useful to hear, thanks. I'm guilty of assuming it's supported in OCP due to being present in this binary! I've been outlining work to support the runtime workflow in our container images under that false assumption. Luckily we have not commit too much time to that yet.

> so it's unlikely that s2i will be extended to implement the runtime-image functionality for the dockerfile generation mode.

In light of the above, that makes sense.

**Comment by bparees** [comment]
> In the context of OCP, is this effectively a multi-stage build, with a source-to-image build (=SourceBuildStrategy?) triggering a second-stage Dockerfile-based build? (Or I suppose one Dockerfile-based multi-stage build doing all the work in one go... although re-implementing all the short-cuts from S2I in a multi-stage Dockerfile sounds a little painful to me)

when OCP's s2i strategy supported this(if it ever did, i'm struggling to find the history now), it was implemented as:

1) start a container from the builder image, inject the source, run the build command
2) save the artifacts produced by the build (this involved a script provided by the builder image to know what to save)
3) start the runtime image, inject the artifacts from (2)
4) save the running container as a new application image

really that's how s2i implemented it and ocp just called s2i.

So you can think of it as similar to how dockerfile multistage builds work, but implemented "manually" in s2i.

If you wanted to reimplement the behavior in OCP i'd say you'd have to options:

1) what you described...  define an s2i build that produces an image containing the application artifacts (but would also include all the build tools)
2) define a multistage dockerfile build that starts from the image in (1), extracts the artifacts and adds them to a second build stage that is based on the runtime image(no build tools)

and set it up so that whenever (1) runs and completes, it triggers (2).

or you can just skip s2i entirely and do a single dockerfile build in OCP with a dockerfile like:

1) from builder image (this can still be the s2i builder image, even)
2) run build steps (this can run the s2i builder image assemble script, even)
3) from runtime image
4) copy artifacts from (2)

that would let you reuse any investment you've made in creating an s2i builder image + assemble script, while producing lighterweight runtime-only application images.
