### ISSUE TITLE
How to build from private git repository?

### ISSUE THREAD

**Issue by forhot2000** [openshift/source-to-image#168]
My git repository is private, how to build from private git repository?

**Comment by bparees** [comment]
STI just runs a git clone:
https://github.com/openshift/source-to-image/blob/master/pkg/git/git.go#L80
so if your environment is setup with a config for your keys/auth to access the private git repo, it should "just work"

**Comment by soltysh** [comment]
@forhot2000 did the solution @bparees provided work for you? If so, can you close this issue, otherwise please provide us with a test case we could test against. Thanks.

**Comment by forhot2000** [comment]
yeh, I have passed the test, thanks @bparees

**Comment by kastork** [comment]
Would it be possible to have some docs on how to do this securely?

**Comment by bparees** [comment]
@kastork what do you mean?  s2i uses your git configuration so doing it securely just means setting up your git config to use security.

**Comment by soltysh** [comment]
@bparees I think we just need to ad a sentence or two that if you want to access private git repo make sure you're having your ssh keys setup and s2i will use them. I'm not sure what will happen if you try to access private repo without ssh keys, iow. when in normal circumstances git asks your for a password, will the same work with s2i, I doubt it, but we could check that and document.

**Comment by kastork** [comment]
Sorry, new to OpenShift.  I've been reading the docs quite a bit, but may be missing something that should be obvious.

I know I need my local machine to be configured to work with a private repo.  This is normal daily business for working with the repo.

I'm talking about deploying that repo up to OpenShift.

The docs say that my local repo needs to have an "origin" remote defined that OpenShift can find.  If that origin is private, then how can OpenShift find it unless it has the keys needed to hit that github or bitbucket private repo?

So...  I presume that "setting up your git config" implies making entries in your OpenShift config files somewhere, or else in the template for the app you are trying to deploy so that the build container has keys or secrets needed so it can clone your private repo whenever it needs to up on the OpenShift cluster.  If this is right, then a little guidance on how to construct the json (or whatever) that provides this info to the build container would be useful. If it is wrong, then I guess I'm missing something central to how the whole source to image system works.

What I mean by "securely" is providing this keymat in such a way that it isn't exposed outside the environment of the build container (as it would be if you checked the keys into the repository)

**Comment by bparees** [comment]
@kastork I see, you're not concerned with using s2i directly.

openshift has docs about how to use private repositories here:
https://docs.openshift.org/latest/dev_guide/builds.html#using-private-repositories-for-builds

that is how you give openshift the keys needed to access your private repository during the build.

**Comment by kastork** [comment]
@bparees Thanks, that's what I was looking for.  And I was right, should have been obvious.  

Thanks for the answer.

**Comment by bparees** [comment]
@kastork yw
