### ISSUE TITLE
run image as part of running source-to-image

### ISSUE THREAD

**Issue by thoraxe** [openshift/source-to-image#180]
It came up in conversation that it might be nice if the sti "program" accepted a flag that would: cause the resulting built Docker image to stay running instead of actually being a created image.

There may be cases where I want to test the result of my STI process locally without having to push the Docker image somewhere.

I guess this flag would essentially cause "run" to be executed immediately after "assemble" inside the instance of the builder image.

It's not a huge time savings, but it could potentially make a few other automation tasks easier... maybe?

**Comment by bparees** [comment]
I would actually describe it as immediately running the output image, as opposed to running the run script after the assemble script.  (among other things, that's much easier to implement).

**Comment by thoraxe** [comment]
I guess I don't understand how it's easier.

If there's an env-var for "run immediately", assemble calls run?

I'm probably missing something.

**Comment by bparees** [comment]
what you're proposing would require every single assemble script be updated to respect that env var and invoke run.

in addition, even if you want to run immediately, we're still going to want to commit the output of your assemble script.  so polluting that container by running the run command in it makes that hard/impossible.

it's just cleaner to run the assemble script, commit the result, and then if desired, launch that image.

**Comment by thoraxe** [comment]
Well, the point of this RFE was to improve time and make for more rapid development cycles. Having to stop the result of the build, commit it, and then run the new image takes time. Sure, it's a trivial amount of time, but still time.

You can kind of look at it both ways. Either we "pollute" the running container and then might have to rebuild, or we "pollute" the local user's Docker with lots of old junk images.

The other thing to think about is that, if we're only using this sti tool to "test" before sending code along somewhere else, it's going to end up getting rebuilt anyway.

I don't think I'm being very coherent.

**Comment by bparees** [comment]
there will be junk images either way, since even with your suggestion you'll get a new image everytime you run STI.

you will have fewer junk containers with your approach (half as many) *if* we don't run with --rm

anyway i take your point, but it also seems like there is value in producing a re-runnable image when you build, even if you want to run it immediately initially.  Which means paying the cost of commit.

**Comment by thoraxe** [comment]
Yes, I think there's value in both sides. Sounds like we're on the same page.

**Comment by soltysh** [comment]
One important question is, should we publish the exposed ports to host by default when doing this run? I assume yes, but what if port is already in use, should we increment number to find first free and tell the user? As for the first question I'm positive, the latter I'm quite reluctant for doing so. Thoughts?

**Comment by thoraxe** [comment]
I would think that if the port is already in use we should probably just fail?

**Comment by soltysh** [comment]
One other question that just popped in my head, what if running image requires passing certain vars, see our DB images (I know these are not the STI case, but I can imagine such requirement). What then? We'll just print the image usage (if one is provided, like in our DB images) and finish. I guess that's acceptable, we tried, but it's up to the user to provide those.

**Comment by thoraxe** [comment]
If the tool can accept the vars to pass to the container, then yeah.

If the container needs vars but we don't offer a way to get them into the container, then the "run" flag becomes slightly less useful...

**Comment by soltysh** [comment]
We do support providing env vars, but only for build process itself. I think OOTB we should provide simple run with exposing the EXPOSE port to host but without any vars.

**Comment by bparees** [comment]
@soltysh if you provide env vars to the build process, they get fed into assemble but then committed into the image so they'd be available for run as well, right?  So i think we're sort of ok there.

For ports, yeah i guess we should try to expose it on the port the image declares and fail if we can't get it, rather than exposing on a random port and making the user figure it out.... though we probably could run it on a random port mapping and print out that mapping as part of the whole flow.

**Comment by soltysh** [comment]
@bparees yeah, but I think I wouldn't want to have an image (even locally) with commited secrets or other env variables, which supposed to be configurable at run time. I'm not sure if docker will let you override those though. But generally speaking this is a big security whole IMHO.

**Comment by bparees** [comment]
@soltysh I think you're beyond the local dev use case now.

**Comment by soltysh** [comment]
@bparees I think that applies to local dev flow as well.

**Comment by bparees** [comment]
@soltysh why do i care if my secrets/config are embedded in my image if i'm not pushing that image anywhere and i'm repeatedly rebuilding the image?

**Comment by soltysh** [comment]
@bparees maybe that's one of my obsessions about security :wink:

**Comment by gabemontero** [comment]
So I've got a prototype of the form @bparees suggested working.  A few devil in the details type items (or perhaps opportunities for folks to educate me on Docker and Go ;-) ) arose when I looked at attaching to the container and piping stdout/stderr to glog so the users could see the output of their build in real time as a way to determine image validity.

1)  If the resulting image from the `sti` invocation results in a long running container, attaching and waiting for the container to exit will not occur, and the `sti` invocation will not exit.  A specific example is the image produced by `sti build git://github.com/bparees/openshift-jee-sample openshift/wildfly-8-centos test-jee-app`

I believe the relevant code in s2i wrt attaching to the container, capturing stdout/stderr, waiting for the container to exit, is here:   https://github.com/gabemontero/source-to-image/blob/master/pkg/docker/docker.go#L420 -L473

Best as I can tell, the WaitGroup API from the sync package *ONLY* reacts to the counter state, with no timeout based bail out.  If I bypass the WaitGroup call in the above code snippet, the `sti` invocation exits, and the image is running in a new container, but we don't get the images stdout/stderr output.  Reworking this logic to somehow employ a wait(timeout) approach is currently not deemed desirable for this item.

2) If I leave the "hanging" behavior in, and ctrl-c out of `sti`, the newly running image is still running, and you have to explicitly stop it with `docker stop <container id>`

So a (at least partial) list of options we could pursue:
have some flavor of --run options that allows you to choose between i) no run (default) ii) run with wait to exit, pipe stdout/stderr, iii) run with no wait and no stdout/stderr

we on iii), and printing out the resulting container id and reminding the user they can use docker cmds to inspect the container/logs/imgaes and stop the resulting container as needed, but solicit feedback.

3) At after some initial discussion, we don't plan on getting into capturing arguments specific to the docker run command.  The user can already set ENV vars with the -e option.  The current plan is to leave it at that.

**Comment by bparees** [comment]
given that even in (ii) the user ultimately has to docker kill the container that got launched, I think we should go with (iii) in which we explicitly tell them "we launched this for you, but you need to go inspect/manage it yourself"  (along with (i) as the default behavior)

**Comment by bparees** [comment]
@thoraxe this was your request so please weigh in.

**Comment by gabemontero** [comment]
It appears there is a fly in the ointment with iii) from the earlier comments that I missed last night.  With either avoiding the `docker wait` equivalent call altogether, or doing it in a separate thread, the container is exiting prematurely and not staying up.  I'm able to grab the exit code on the container when waiting on a separate thread, and it appears to be 137.  There are some google hits on this, but nothing with a solution per se.  What is weird is the process does not even show up as having started then exited in docker ps -a. 
Like it never started unless I call wait in-line.

I'll experiment some more, but for images/containers that stay up, we may be left with
a) printing a banner like reminder to tell them to ctrl-c and inspect the image like before, don't pipe stdout/stderr to glog
b) or do pipe stdout/stderr for glog, and hope our banner reminding them to ctrl-c does not get lost in the shuffle as their image output comes out.

Pros and cons with each ...a) might be the lesser of the evils here.

Needless to say, this is getting a bit messier for images that stay up.

**Comment by bparees** [comment]
definitely prefer (a) but we ought to be able to launch the container and then exit.  I wonder if the s2i process is simply exiting before the call to the docker daemon is complete.

you said you're getting a 137 rc?  i'm confused about the circumstances under which you're getting that given that docker ps -a doesn't even show the container having run.

**Comment by gabemontero** [comment]
Yep, that was one of my theories.  The `sti` process exiting has something to do with it, but it appears that the way it exits matters.  In other words, ending "naturally" as the last instruction completes results in different behavior than a Ctrl-C.

Here's what I've tried:
1) First call "InspectContainer" on the docker client and confirm the container was in Running state before moving on.  That did not help.  And it exited too quickly to see stdout/stderr from the image.

2) What I was trying to avoid ... just adding sleeps.  With a sleep of 5 seconds, I saw what looked like the complete set of stdout/stderr from the image.  But when I run `docker ps -a` after `sti` completes, the container is gone - not even listed as exited.

3) With a sleep of 60 seconds, I have time to run `docker ps -a` while `sti` is still up.  I see the container.  When the 60 seconds is up, and `sti` exits, then `docker ps -a` no longer shows the container - does not even indicate that it exited.  Saw the same set of image stdout/stderr show up via glog.

4) As a reminder, employing Ctrl-C once `sti` has invoked the `docker wait..` equivalent leaves the container up.

So some form of configurable version of 3) would perhaps/conceivably be more usable than prior options.

I'll start looking at how origin/k8s starts containers, and see if there are any differences in how the fsouza docker client is leveraged.  Perhaps since openshift stays up, this behavior is masked ?  Curious to see if that is the case.

But I'll probably reduce the cycles on this one for the next little bit and dive into extended tests.

**Comment by bparees** [comment]
sounds like you're running the container with the equivalent of "docker run -rm" which removes the container after it terminates.  that would explain it not showing up in docker ps -a later.  A quick survey of the client library doesn't show me a way to control that behavior, unfortunately, but we don't necessarily have to change it as long as we're convinced the container is being run when it's supposed to be run.

if you cntrl-c while s2i is sleeping in (3) does that immediately kill the running container?  i'm guessing not, but might be worth a test.  Seems like there's some cleanup/signal propagation that only happens when s2i exits cleanly, not when it gets cntrl-c'd.

**Comment by gabemontero** [comment]
Ctrl-c while s2i is sleeping leaves the container up - i.e. the same as when we ctrl-c during the `docker wait ..` call.

And my interpretation of the fsouza client library is the same as yours, in that they do not expose the -rm switch.  RE: https://github.com/openshift/source-to-image/blob/master/Godeps/_workspace/src/github.com/fsouza/go-dockerclient/container.go#L405-L447

And the google hits I  got with the exit code 137 that I mentioned earlier spoke to signal handling, so concur there as well wrt your point about the cleanup/signal handling differences with clean exit vs. ctrl-c.

My search through k8s revealed no differences in the low level starting of containers either via the fsouza Godeps.

I'll spell out the approach I referenced in today's scrum (granted your initial reaction was not exactly exultant, though I'm not thrilled either):
1) change --run= to accept integers instead of boolean
2) --run=0 means we wait forever (i.e. `docker wait`) and we both doc in the usage help and online doc, and print a banner during execution, stating that you have to ctrl-c to exit `sti`
3) otherwise, --run=<integer> specifies the number of seconds we sleep before exiting
4) we explain in docs that ctrl-c leaves the container up, clean exit does not

I feel dirty even spelling that out, but pending a better suggestion or just punting on this, that is where I'm at on this one.

**Comment by bparees** [comment]
@gabemontero maybe you can do something with this to stop the container:
http://nathanleclaire.com/blog/2014/08/24/handling-ctrl-c-interrupt-signal-in-golang-programs/

**Comment by thoraxe** [comment]
I'm fine with @bparees suggestion from https://github.com/openshift/source-to-image/issues/180#issuecomment-128103661

Although I'm wondering now about being able to edit the filesystem in the running image, since you can't do that in the "built" image later... but since the build needs to be able to write, perhaps this is the way we can achieve the "hot edit" stuff that we wanted? I forget which issue that is.

**Comment by bparees** [comment]
since this is running via s2i directly, not via openshift, the container we ultimately run (the one running your application code) will be running as the same user who did the assemble/build steps.  so you'll be able to exec in and modify code in this scenario.  But it will have no impact on the ability to do so when running in openshift.

**Comment by gabemontero** [comment]
@bparees the signal handling got us the consistent behavior we wanted - thx again for the tip.

So now, we can pipe stdout/stderr to glog, but the customer can also use docker commands to inspect the container running the image (the code prints out a easy to spot message citing the container id).

Once the customer ctrl-c's, `sti` exits and cleans up the running container.

Aside from scrubbing the code prior to submitting the PR, I've got to tweak the origin doc.  Assuming that is all, I should have a PR late AM / early PM on Wednesday.

An initial scan of the existing unit tests in source-to-image did not reveal any useful suggestions of note there - nothing specific to start up options, and this change is outside the existing algorithm.  I'm leaning toward no unit test, but will take any suggestions.

**Comment by soltysh** [comment]
@gabemontero can we see your POC as a PR, I'd like to give it a try and then provide some useful feedback.

**Comment by bparees** [comment]
@gabemontero sounds good to me, nice work!

**Comment by gabemontero** [comment]
Absolutely @soltysh I will be doing that later today (have an appt this AM so it may be after lunch US EST).  Among other things, I'm curious about your take on where I hooked in the running of the container (among other things, I decided *NOT* to use the PostExecute phase).

Thanks @bparees

**Comment by soltysh** [comment]
> (among other things, I decided NOT to use the PostExecute phase).

Perfect, I'd expect this to be completely separate from the Build process withing S2I, that's why I'd like to see the code behind it.

**Comment by gabemontero** [comment]
OK cool.
