### ISSUE TITLE
support building images not based on the builder image

### ISSUE THREAD

**Issue by ibotty** [openshift/source-to-image#265]
e.g. to support statically linked applications (golang), etc.

I can try to implement that myself, if given some pointers on where to start.

**Comment by bparees** [comment]
we're carrying a feature request for this on our trello board:
https://trello.com/c/MWUAjl6k/237-13-extended-builds-separate-mvn-vs-jboss-build-future

i think this feature is going to need some design work because we need to decide how we're going to build in one image and then extract the build content and layer it into the runtime image (sort of like save-artifacts does) so i don't know that there's going to be an easy way for you to contribute it, but we can definitely discuss some design thoughts in this issue if you have some.

**Comment by ibotty** [comment]
Is there some way to draw attention to this issue? I'd like to move that ticket forward.

**Comment by ncoghlan** [comment]
Since the current behaviour is useful for local development purposes, I posted the following suggestion to the trello card:

* add a `build-devel` subcommand that focuses on the "local development" use case (where having a full build and debugging environment available inside the image is useful)
* add a `build-release` subcommand that focuses on producing lean images for use in automated CI and eventual deployment as production services
* advise folks using `build` currently that the behaviour is going to change and they should switch to using `build-devel` if they want to continue using that model
- once `build-release` was working satisfactorily, change `build` to be a shorthand alias for `build-release`

**Comment by bparees** [comment]
@ncoghlan that's an interesting idea but fundamentally using this feature is going to require that 2 images be provided to s2i.  One that contains the build packages, and one that contains the runtime packages.  So rather than introduce new build commands, i think we just want to introduce new args to the existing build commands.  One to specify the builder image and one to specify the runtime image.

**Comment by ncoghlan** [comment]
That approach sounds good to me, since supplying a single image will retain the current behaviour, while supplying both images would opt in to splitting the output.

**Comment by mfojtik** [comment]
@ncoghlan @bparees this will require support in the image, right? If you want to have 'development' mode enabled, that means you need to use the builder image that has all necessary tools installed.

I think what you're suggesting is already possible, for example I can have 2 images:

`mfojtik/php-builder-release` and `mfojtik/php-builder-devel`. For development I will use the later and for 'release' I will use the first one.

Also having a 'development' usually means different configuration for assemble/run. The lesson we learned from our builder images is that this 'enablement' is always different (RAILS_ENV in ruby vs. DEBUG=true in python), so there is no 'universal' way for this. Unless you want to provide `assemble` and `assemble.devel` scripts.

**Comment by ncoghlan** [comment]
Sorry, I confused the issue by mentioning debug mode. Even release builders will want to separate build dependencies (e.g. maven, pip, bundler, npm, bower, grunt, gcc) from a more stripped down runtime environment, and that's the main focus here.

**Comment by mfojtik** [comment]
@ncoghlan I think that is already possible by using different image for building the release and building 'development' application image. But maybe I'm missing something.

**Comment by jimmidyson** [comment]
@mfojtik There is normally a lot of stuff in the builder image that isn't required at runtime. e.g. in a Java Maven S2I there is Maven itself. Then the Maven build will pull down lots of plugins & their dependencies that are only required at build time. Even the chance of JDK at build time vs JRE at runtime.

So from my PoV the e.g assemble script being able to export a tarball containing only runtime dependencies that can be layered on to a runtime base image would significantly shrink the runtime image size.

**Comment by ncoghlan** [comment]
Exactly. In my case, for a Python application paired with a Patternfly/AngularJS front end, I need pip in the builder to bring in the back end dependencies, and tools like npm, bower & grunt for the front end. I'll also end up with a lot of cached artifacts that I may want to keep around for the next build (if I'm not using my own central pre-built artifact store in something like Pulp or pinrepo).

However, I *don't* need any of that in the runtime container - I want that to be as small as possible.

An alternative to modifying the existing `assemble` script might be to have a separate `export-paths` file that defines which directories are needed to produce a suitable runtime image.

**Comment by bparees** [comment]
@ncoghlan yup that's the story we want to implement.  it is much like the current incremental flow.  today with the incremental flow you perform an s2i build, then later you pull content out of the result image from the first build and inject it into the second build flow.

with this we'd do pretty much the same thing but all at one time:
1) invoke s2i using the builder image
2) copy the produced artifacts out of the builder image
3) invoke s2i using the runtime image and injecting the content from (2)

**Comment by ncoghlan** [comment]
That sounds good to me - I'll continue with the migration of my current app to the s2i builder model, and not worry too much about the size of the resulting image until after this feature is available.

**Comment by mfojtik** [comment]
@ncoghlan another option is to strip the output image by removing all the development things and then squashing (after you `sti build`)

**Comment by jorgemoralespou** [comment]
@mfojtik But that will have inpact on build time.

From my PoV looking for a solution to this would solve many different issues:
- Runtime images (eap, wildfly, tomcat, node.js,...) will be easier to produce. Hence more runtime images wiill come into OpenShift from community faster
- Builder images (maven, gradle, ant, npm, rake,...) will easier to produce. Hence more builder images wiill come into OpenShift from community faster
- Pushing generated image (runtime + built artifact) will be faster
- Generated image will be smaller (only repushing generated artifact on every rebuild)
- Will allow for bringing caching of dependenciies (if we can constrain where these builder images land, and have shared storage for them)
- Allow for better local dev experience as devs can use locally (in plain docker in their laptop) and remote (in openshift) the same images for building and  running. E.g. "sti run maven eap ."
- Can be easily complemented with "oc sync" to have same local dev experience to enhance the building workflow (as sti will not do testing, etc...) (E.g. maven clean test openshift:deploy eap"  

Not sure the amount of effort is needed for this feature, but for sure that the benefit it provides will greatly pay off. I've used a lot of imagination in my disertion, but for sure, this could be top feature for dev experience.

**Comment by mfojtik** [comment]
The discussion mostly moved here: https://trello.com/c/4bxcGz5w/750-remove-git-support-from-s2i
@bparees I think we can close this (CLOSED UPSTREAM ;-)

**Comment by bparees** [comment]
@mfojtik I agree we can close, i don't agree the card you referenced is the right one.  it's still this card:
https://trello.com/c/MWUAjl6k/237-13-extended-builds-separate-mvn-vs-jboss-build-future

The card you referenced should only be about simplifying s2i, not adding other functionality.

Whether we ultimately need s2i to be able to take its input from an existing docker image, or if that will be origin behavior, we can determine as part of completing that card.

**Comment by ncoghlan** [comment]
Please don't make a usable s2i depend on having an OpenShift installation
available just because that's better for Red Hat's business plans. If I'm a
native Linux developer pushing relatively simple images to DockerHub, I
don't want to run an entire PaaS VM locally just to build clean images.

If s2i decides that only OpenShift users are worth caring about, then I'll
have to start exploring alternative solutions that are interested in
handling the portable standalone container image use case. That's doable,
of course, but seems pointlessly duplicative of the bulk of s2i's
functionality.

**Comment by bparees** [comment]
@ncoghlan thanks for sharing your concerns, that's definitely not the idea here.  What we are trying to do is simplify the responsibility of s2i.  

The idea is that s2i should consume source.  Getting that source to s2i should not be a problem s2i tackles, because there will always be one more SCM, one more storage mechanism, etc, that we'll never keep up with.  Right now the s2i git cloning functionality has a number of holes in it, which is what has lead us to this conclusion that we should let git do what git is best at, and let s2i do what s2i is best at.

So that means in the future you might run git clone yourself, and then invoke s2i against the locally cloned directory, rather than running s2i against a remote repository (which, today, results in s2i git cloning and then running against the local files anyway, so nothing is really changing except that the git clone is performed by the git binary explicitly).

How does this play into the extended build functionality of separating builder images and runtime images?  Well it would mean in the future you will be able to:
1) run an s2i build using a builder image (only contains maven, for example) which will produce an image containing your WAR file
2) use docker cp to pull the WAR file out of the image from (1)
3) run an s2i build using the WAR file as your input and a "runtime" image as your builder (eg something with an application server in it) and get a resulting application image with your chosen runtime+WAR file.

We've also considered the following flow:
1) run an s2i build using a builder image (only contains maven) which streams the resulting built artifacts as a tar stream to stdout
2) pipe that output into a second s2i build, where s2i can handle an input tar stream

Do either of those plans satisfy your concerns?  Ultimately anything more "first class" that s2i did would just be doing one of those 2 flows except under the covers, and again we're trying to simplify s2i down to very basic flows that can be piped together, as that fits the unix philosophy better, along with making it more maintainable and testable.
