### ISSUE TITLE
Add "docker://" source type

### ISSUE THREAD

**Issue by mfojtik** [openshift/source-to-image#297]
Invoking the `sti build docker://image/path builder target`  should pull the `image` and then extract the `/path` from it and use it as a source, where the `/path` does not necessarily need to be a GIT repository.

This allows us to use local host directory as a source in OpenShift without pushing the code to external GIT server. It also allows bundling stuff like secrets or binary artifacts into Docker image (in case you don't want to use GIT).

Having this supported here should enable this in OpenShift as well which also means you can create docker image with the source you have locally, push it into OpenShift internal registry and use it as a source for the build.

@smarterclayton @bparees just want to capture this idea, I think it is pretty neat :)

**Comment by mfojtik** [comment]
@bparees this also allow us to do S2I build pipeline like:

1. `s2i build file://java-app java-devel-builder java-app-with-dependencies`
2. `s2i build docker://java-app-with-dependencies/war java-runtime final-app`

**Comment by mfojtik** [comment]
related to: https://github.com/openshift/source-to-image/issues/265

**Comment by mfojtik** [comment]
also `docker cp` supports this:

> Using - as the second argument in place of a LOCALPATH will stream the contents of the resource from the source container as a tar archive to STDOUT.

so we can 'stream' the directory in container like we do currently.

**Comment by bparees** [comment]
i think that's what @smarterclayton was proposing as an alternative way to do binary sourced builds.

and i think if people hate the idea of binaries in a git repo, this is arguably worse :)  but i'm sure i'm going to lose that debate.

**Comment by mfojtik** [comment]
related trello card: https://trello.com/c/MWUAjl6k/237-13-extended-builds-separate-mvn-vs-jboss

**Comment by smarterclayton** [comment]
We kind of need this for other flows.  At some point we'll have to decide
whether we want to save the source input for a build in an image... for
instance, as a multistage builder.  Not sure that's the *best* model, but
it's potentially important.  We need to discuss it.

**Comment by mfojtik** [comment]
@smarterclayton I thought this might resolve the "extended build" problem, where you want to have builder with all dependencies (typically maven/etc) and then runtime builder that will just extract the "war(s)" and place them into right locations... You can do that using docker:// as a source path where you specify the image built by first builder and location from where we copy the wars...

**Comment by bparees** [comment]
@mfojtik there's also probably value in using this to allow multiple inputs to a build.  @smarterclayton's dockerfile implementation has already kinda started down that path (you can provide a git repo and a dockerfile as inputs).

we should think about evolving to a general solution where you can supply N inputs (source, maybe another source, dockerfile, docker image, etc) with priorities and we'll copy it all down (in reverse priority order to allow for overwriting).

**Comment by smarterclayton** [comment]
I kind of want to move some of this behavior outside of the core STI path
though - instead of having STI be doing all this magic, have this magic be
done first, then call STI on a directory (the core STI code).  The STI top
level interface is becoming too coupled to the mechanics of this - I don't
want the STI options object to grow infinitely.  My PR to binary build
actually takes the first step to that, by removing the responsibility of
assembling input from the STI download path, and instead making it external.

**Comment by smarterclayton** [comment]
Further clarification:

STI command - should know about getting input and then invoking STI on it
Docker builder - should know about getting input and then invoking Docker
on it
STI builder - should know about getting input and then invoking Docker on it

The "getting input" part is really not specific to STI, so it needs to be
the step before STI is invoked.  That code canonically lives in both STI
and origin today - the helpers and parts of steps can live in STI, but the
process of turning an OpenShift build into that set of inputs is a
responsibility that lives in the origin-*-builders.  We shouldn't do an
infinite amount of setup in the STI command - I don't think that's its role.

**Comment by bparees** [comment]
@smarterclayton i like the separation but it is going to be problematic if we ever want s2i to natively support extended builds since that, as @mfojtik notes, would likely be implemented in this way.

if we decide that extended builds will not be an s2i feature, but instead will be an openshift specific feature, then we can more easily go that way.  (openshift would be responsible for constructing an image containing a war, and then pulling down that image, extracting the war, and invoking s2i against the war)

**Comment by smarterclayton** [comment]
Extended builds as an s2i call still has to be orchestrated.  Extended
builds are similar to input - they should be above the core "do the s2i
build" logic.  The CLI certainly would have no problem invoking them in
order.

**Comment by smarterclayton** [comment]
I.e. a CLI that said "extract input - perform build 1 - perform build 2"
calling three discrete steps in the s2i code base.  I don't think s2i
*should* be as sophisticated as the builders in downloading source - in
fact I would say that we would never add things like SVN / HG builds to s2i
(because you can just run them locally) but we'll add that in Origin.

**Comment by smarterclayton** [comment]
I'm going to go a step further and say that s2i should not be responsible
for downloading source code.  It's something external tools can do better.
It's probably ok if it recognizes it's in a git repo and sets source
labels, but that's it.

Users on the cli can set up their source using their existing tools.  S2i
only cares about a directory.  We should stop endorsing that flow for
input.  It's ok if s2i knows how to do the extended flow and artifact flow,
but otherwise it's not responsible.

@mfojtik that applies to dockerimage:// - it basically removes that problem
from s2i

On Oct 11, 2015, at 6:33 PM, Clayton Coleman <ccoleman@redhat.com> wrote:

I.e. a CLI that said "extract input - perform build 1 - perform build 2"
calling three discrete steps in the s2i code base.  I don't think s2i
*should* be as sophisticated as the builders in downloading source - in
fact I would say that we would never add things like SVN / HG builds to s2i
(because you can just run them locally) but we'll add that in Origin.

**Comment by smarterclayton** [comment]
S2i should also be able to take a tar (possibly gzipped) via stdin
eventually.

With a structure like this, we can break the origin builder pod into two
parts - one that prepares input and puts it into a volume mount, and one
that waits for a signal via the FS (in a prestop hook or similar) before
invoking s2i on that directory.  That provides security isolation in terms
of remote execution flaws with git.

On Oct 11, 2015, at 6:46 PM, Clayton Coleman <ccoleman@redhat.com> wrote:

I'm going to go a step further and say that s2i should not be responsible
for downloading source code.  It's something external tools can do better.
It's probably ok if it recognizes it's in a git repo and sets source
labels, but that's it.

Users on the cli can set up their source using their existing tools.  S2i
only cares about a directory.  We should stop endorsing that flow for
input.  It's ok if s2i knows how to do the extended flow and artifact flow,
but otherwise it's not responsible.

@mfojtik that applies to dockerimage:// - it basically removes that problem
from s2i

On Oct 11, 2015, at 6:33 PM, Clayton Coleman <ccoleman@redhat.com> wrote:

I.e. a CLI that said "extract input - perform build 1 - perform build 2"
calling three discrete steps in the s2i code base.  I don't think s2i
*should* be as sophisticated as the builders in downloading source - in
fact I would say that we would never add things like SVN / HG builds to s2i
(because you can just run them locally) but we'll add that in Origin.

**Comment by bparees** [comment]
i definitely like the idea of paring s2i back to "provide a local input and an image to build it with", as we are spending too much time juggling functionality between openshift and s2i today and having bits scattered between the two. 

However I do worry that it limits the value of s2i as a standalone tool.  If you want to use it as a standalone tool and not in openshift, you will need to bolt more workflow around it.  For example we just added the ability for s2i to determine the git commit of the input and set it as a label on the result image.  It sounds like with your proposal, s2i would have to take the commitid (and any other label values) as explicit inputs provided by the caller (the caller being openshift, or some other build workflow).

And we definitely have people using it in this way today (people opening issues against s2i because of various bugs/limitations in how s2i processes input paths).

I suppose we could take a middle road approach and stop using s2i in this way from openshift (start just doing the git cloning in openshift and then invoking s2i on the local directory, instead of relying on the s2i git clone behavior), while still leaving the capability in s2i to also download/clone source, but stop augmenting that support (eg not adding support for docker images as an input source).

**Comment by mfojtik** [comment]
+1 after some thinking I agree that we should not go too far providing different download methods for every possible SCM or download source in S2I, because we end up as SCM abstraction layer supporting infinite number of download methods.
Maybe another idea could be to start a new project that will deal with different source download methods, such as Git, SVN, Mercurial or Docker. We can then re-use this library in both OpenShift and here. This will de-duplicate the code we have in OpenShift and allow us extend the variety of SCM we support.

Currently we already have support for running S2I without GIT (file:// with non-git repository), we can add support for streaming source in from a tar file.

**Comment by soltysh** [comment]
@mfojtik we've already discussed that idea (at least partially), and there's even a card for that https://trello.com/c/cmLqfEiU/572-13-make-git-and-other-scm-code-a-go-package-inside-s2i-and-openshift

**Comment by smarterclayton** [comment]
What's the value of the new project?  There's already projects for
downloading source from Git, SVN, Mercurial, etc.  It's called Git, SVC,
Mercurial, etc.

I'd like to restrict the integration points beyond s2i and your source to
"here's a directory, tar, or file that is the input to a build".  That's
it.  A developer building s2i with local source can already script and
manage the source code without S2i being involved.  Remote source needs to
deal with auth, certificates, and locations, and that's just not in its
remit.

**Comment by mfojtik** [comment]
@smarterclayton we are downloading the remote sources right now (using git clone). We are also using GIT to read the metadata about the sources (commit-id, author, message, etc...). I'm fine with restricting S2I to only deal with "here is a tar stream" or "here is a directory", build the app from it. Since we already label the image in OpenShift, we don't need the labels that S2I provides other than for supporting "rebuild". If "rebuilding" the application image that you built locally is not that important, then we can strip down S2I to deal just with directories and tar streams.

**Comment by soltysh** [comment]
I like the idea a lot. As for the metadata @mfojtik is talking about. This can be injected along with the sources as well, so that's not a problem imho.

**Comment by mfojtik** [comment]
@soltysh it could, but you will have to supply that manually or script it :-) Or we can provide some nice shell wrappers that will extract the metadata from the GIT repository and set it to `s2i` command.

**Comment by soltysh** [comment]
:+1:

**Comment by mfojtik** [comment]
`s2i-git`, `s2i-svn`, etc...

**Comment by mfojtik** [comment]
@bparees looks like we have good architectural topic for today ;-)

**Comment by smarterclayton** [comment]
You can grab metadata from a directory - just as long as it's a
replaceable, abstractable set of code that's reusable elsewhere.

**Comment by mfojtik** [comment]
closing this as we decided to approach this differently (remove GIT from s2i and support just tar streams)
