### ISSUE TITLE
Unhelpful error message if .git project repository is empty

### ISSUE THREAD

**Issue by strzibny** [openshift/source-to-image#298]
e.g. I have a not-empty project repository with my Ruby app, but with an empty .git repository. Then the following error message is misleading since I as a user have nothing to do with `/tmp/src`.
```
s2i build file:///$PWD openshift/ruby-22-centos7 newapp
I1002 08:32:59.352893 20229 sti.go:406] ---> Installing application source ...
E1002 08:32:59.358128 20229 util.go:85] cp: cannot stat '/tmp/src/.': No such file or directory
``

**Comment by bparees** [comment]
sorry i'm not clear on your terms.  does your local directory contain anything or not?

**Comment by strzibny** [comment]
`.git` repository is empty, the project can be there but it's ignored anyways.

**Comment by mfojtik** [comment]
why you have empty .git folder in your project folder?

**Comment by strzibny** [comment]
It was by accident ;) but I had hard time understanding what's wrong because I thought there is an problem of the image side e.g. the src is not mounted.

**Comment by bparees** [comment]
at first i was going to say we should always copy the source (instead of cloning the source) when the directory is local.

but given that we attempt to include commit information in the built image if your source was a git repo, i'm going to say the current behavior is correct but we can definitely try to improve the error message i guess.

**Comment by mfojtik** [comment]
we detect local repository by looking if there is a .git directory in the
folder. we can check if it is empty, but I don't want to make it more
complex as it is pretty complex already :)

**Comment by strzibny** [comment]
I believe that's a behavior of s2i, it's not a good goal to fix that in every s2i assemble script right? Or do I have to check in Ruby assemble script that /tmp/src/ really exists? What I would expect is that the directory  exists, that's IMHO the right behavior. Yes it can be empty if the .git is empty, no problem. but the path itself should exists.

**Comment by bparees** [comment]
no, not suggesting it be fixed in the assemble scripts.

but again...you pointed s2i at a git repo, s2i is primarily intended to work with git repos.. so we assume you want us to operate on the git repo content, not the directory content.  so i would not be in favor of changing this behavior beyond a better error message/warning.

**Comment by strzibny** [comment]
> . so i would not be in favor of changing this behavior beyond a better error message/warning.

If you look at the name of the issue, that's exactly what I am suggesting. But as I thought more about it, perhaps /tmp/src should exist anyway. Then I can freely copy files from there (be it empty or not) and I can get the correct message later ("Could not locate Gemfile"). Which would tell me that Gemfile is missing....and I at least know it's not there.

**Comment by bparees** [comment]
> If you look at the name of the issue, that's exactly what I am suggesting. 

yup, understood, just wanted to close the loop on the idea i was floating earlier about whether we should handle this differently (eg always use "copy" instead of "clone" when the source location is local disk)

> But as I thought more about it, perhaps /tmp/src should exist anyway.

honestly i'm a bit surprised it doesn't but yes, ensuring /tmp/src always exists sounds like a potentially viable approach.  will have to look at what we're doing when creating the archive that causes it to not exist...  i guess maybe our tar logic is skipping empty directories.

**Comment by mfojtik** [comment]
The original issue was about the directory reported as "misleading". Can't we just change the path to /tmp/src and copy from ".", so that directory name will disappear from the error message?

**Comment by rhcarvalho** [comment]
> Can't we just change the path to /tmp/src and copy from "."

That would require changing all assemble scripts :(
