### ISSUE TITLE
Not possible to include/restore .git directory via .s2iignore

### ISSUE THREAD

**Issue by babelop** [openshift/source-to-image#299]
It would seem the _default_ [ignore expression](https://github.com/openshift/source-to-image/blob/master/pkg/tar/tar.go#L25) cannot be overriden by a `.s2iignore` file.

Specifically it is not possible to ensure the source `.git` directory is tarred over to the new image **if specifically desired**. At least no pattern I've included has been able to accomplish this. The addition of the `.s2iignore` file doesn't automatically override the default pattern, and using a **not** expression doesn't work either.

The use-case in particular would be that some deployed applications benefit from information on the specific build (like it's commit id). I'm going to open a suggested feature improvement with regards to that example, but generally speaking it should be possible to have the `.git` directory deployed as a workaround when necessary. The nature of a default exclusion pattern would imply that it can be overridden.

**Comment by gabemontero** [comment]
Interesting idea.  A couple in internal implementation points that have some relevance:

a) the current tar support does have a public method to override the exclusion pattern (https://github.com/openshift/source-to-image/blob/master/pkg/tar/tar.go#L64-L66), but we currently do not bubble that up to a `s2i` command line option that would allow you to set it

b) at the moment, the exclusion pattern leverages golang regular expressions, where as the .s2iignore file leverages golang Glob's a la the docker ignore files ... so different algorithms here, and not as clean an overlap of use case as one might think. 

Given these facts, I'm inclined to simply expose a new `s2i` cmd line option to allow users to set the exclusion regular expression string for s2i's tar, and not muddy the waters by bringing .s2iignore into this space.

@binarybabel - would that suit your needs?

@bparees - please chime in here or let's discuss offline when you get the chance.

**Comment by binarybabel** [comment]
@gabemontero That would fit our needs, at the moment, but here are a couple of observations:

- Even though the pattern mechanics are different, the presence of .s2iignore could be seen as replacing the default pattern, eliminating the overlap. Users still wishing to exclude .git directories could then add them to their ignore file. Admittedly though, that's a user-design question as to what is the preferred behavior. However the amount of time I spent trying to figure out when/where/why all .git directories were missing makes me think the existing system isn't perfectly intuitive.
- Something to keep in mind is that the default exclusion pattern can also interfere with save-artifacts restoration. Specifically bundler installed gems from github sources. The next bundle will fail because their .git directories (just like the root .git directory) are missing. Currently the only way around that is to remove those gems and let them install fresh, I.E. `rm -Rf bundle/ruby/bundler bundle/ruby/cache/bundler` Granted, that's ruby specific, but I feel that issues like these will keep popping up.

My point being that excluding .git directories isn't bad default behavior, but can cause real issues. So long term I think an SCM/repo level way of configuring this is necessary (as opposed to external dc/pod level options). My vote would be to just have the presence of .s2iignore bypass the default pattern.

**Comment by bparees** [comment]
> My vote would be to just have the presence of .s2iignore bypass the default pattern.

honestly we probably want to do both.

1) flag that lets you override the default exclusion pattern from the CLI
2) if there's a .s2iignore file, don't apply the default exclusion pattern and use the .s2iignore instead.

@soltysh what do you think?

**Comment by soltysh** [comment]
Frankly said I'd ho with just .s2iignkre file without introducing yet
another cli option. It's simpler and cleaner solution than doing the mix.
The other thing that also seems to make sense, is to completly drop
excluding something when tarring, unless there's a good reason to have
those defaults,  I don't remember any atm.

**Comment by bparees** [comment]
yeah i was curious where that default exclusion came from too.  i guess we figured there's no likely need to have .git history in your final application image (and probably some good reasons not to).

i can live with the "just .s2iignore" path (and it sounds like @binarybabel can too), just thinking it kinda sucks to have to create that file in your source repo to do a simple override.  but sure we can start there.

**Comment by gabemontero** [comment]
Forgot about this one and *finally* dug it up today.

Turns our, since last we talked, the exclusion pattern *was* surfaced as a `s2i` arg [here](https://github.com/openshift/source-to-image/blob/master/cmd/s2i/main.go#L181) as part of my fix for https://github.com/openshift/source-to-image/issues/457 (and I obviously forgot to cross reference with this one)

@bparees since option 1 from the old discussion above has been added, do we still want to do option 2 at this point ?

**Comment by gabemontero** [comment]
Updating .s2iignore was in fact dismissed in the discussion in https://github.com/openshift/source-to-image/issues/457

**Comment by bparees** [comment]
seems good enough to me.
