### ISSUE TITLE
Maven Artifacts All Redownload On Every Build

### ISSUE THREAD

**Issue by SecurePaaS** [openshift/source-to-image#409]
I've noticed everytime my codebase rebuilds with STI that all the maven architects need to be redownloaded.  Is there anyway to cache artifacts so compilation can happen faster?  Note: I'm running STI via Openshift 3.1.  I assume simply persisting the m2 directory and sharing it would fix this problem but have no idea how to go about doing this.

**Comment by bparees** [comment]
See the discussion of how to enable incremental builds here:
https://docs.openshift.org/latest/dev_guide/builds.html#incremental-builds

not all s2i images support incremental builds, but the EAP image provided with openshift does and when enabled, it will reuse the .m2 directory from the previously built image.

**Comment by SecurePaaS** [comment]
Thanks!  That worked!  For future reference to anyone curious, you can edit your build strategy by editing your build config using "oc edit bc -o json" and then saving the corresponding changes as depicted in the link above

**Comment by SecurePaaS** [comment]
@bparees - I thought it was fixed but it appears its not saving the artifacts because /usr/local/s2i/save-artifacts is not found.  For reference, I'm using the provided jboss eap image as my base.  Is there anything further I should have to do to make this work?

**Comment by bparees** [comment]
you're using registry.access.redhat.com/jboss-eap-6/eap64-openshift ?

```
$ docker images | grep jboss-eap
registry.access.redhat.com/jboss-eap-6/eap64-openshift                      latest              cd9c11961578        7 weeks ago         1.207 GB
```

```
$ docker run -it registry.access.redhat.com/jboss-eap-6/eap64-openshift ls /usr/local/s2i
assemble  common.sh  run  save-artifacts
```

**Comment by SecurePaaS** [comment]
I don't have administrator access to the local systems running openshift and can only use the oc tools / web interface at the moment.  I'll see if I can get someone with access to ensure its the latest image and run the docker command you specified but if it helps, I used the only EAP image available in the web interface to spin up this project.  I'm sitting on Openshift 3.1 so I assume its the latest supported version of the images installed.

**Comment by bparees** [comment]
If you edit your buildconfig to point directly to the docker image, instead of an imagestream, and specify "forcePull=true" on your buildconfig, you'll get the latest image pulled down when your build runs.

https://docs.openshift.org/latest/dev_guide/builds.html#s2i-force-pull

basically your build config will look something like:
{
  "strategy": {
    "type": "Source",
    "sourceStrategy": {
      "from": {
        "kind": "DockerImage",
        "name": "registry.access.redhat.com/jboss-eap-6/eap64-openshift" 
      },
      "forcePull": true 
    }
  }
}

(notice the from "kind" changes from ImageStreamTag to DockerImage)

**Comment by SecurePaaS** [comment]
made those changes and it pulled the latest image but it still didn't find /usr/local/s2i/save-artifacts.  Will it not show up until the second build after switching images?

**Comment by bparees** [comment]
Yes that's likely the case since it is invoking save-artifacts from the previously built application image.

So the first time you did it, the previously built image was one that wouldn't have included save-artifacts.

**Comment by SecurePaaS** [comment]
So idk if its working or not yet bc on the next build it started pulling the image again (so its taking forever).  I thought this would have happened so I preemptively removed the '"forcePull": true ' from my build config prior to pushing any changes but it still happened.   Why is it pulling the image?  Because it's linked to a DokcerImage rather than an ImageStream?

**Comment by bparees** [comment]
I'm not sure which image you're seeing it pull in this case, but when you enable incremental builds, it will always pull the previous application image when starting the build because it needs to ensure the previous image is available so it can retrieve artifacts from it.

That pull should be relatively quick since
1) that image is coming from the openshift registry, not dockerhub (it's your applicaiton image, not the original eap s2i image)
2) assuming the previous build ran on the same node as the current build is running, the image should already be present so the pull should just be a matter of confirming checksums.

if you provide level 5 build logs i'll be happy to take a look though.

**Comment by bparees** [comment]
(and yes, removing forcePull was the right thing to do once you'd gotten the new image updated, though again if you have multiple nodes in your cluster, you need to ensure all the nodes have the latest s2i EAP image before you remove that, or you're going to have inconsistent behavior)

**Comment by SecurePaaS** [comment]
Ahhh that's probably why I saw it pulling again.  It was probably starting
the build on a different node needed to pull down the image for that note
specifically.  I'll check into this tomorrow to see if it works once all
the nodes have been updated.

**Comment by bparees** [comment]
Any luck today?

**Comment by SecurePaaS** [comment]
Thanks for checking back.  My entire openshift environment crashed today so
we are working on fixing it at the moment.  Until I can fix it, I won't be
able to validate the fix.

**Comment by bparees** [comment]
closing based on age, will reopen if you have an update.
