### ISSUE TITLE
TestLayeredBuildNoTarNoName is flaking on windows

### ISSUE THREAD

**Issue by bparees** [openshift/source-to-image#533]
```
I0708 12:22:39.758507   10220 tar.go:308] Adding to tar: /tmp/s2i263248273/upload/src/README.md as src/README.md
I0708 12:22:39.758560   10220 tar.go:308] Adding to tar: /tmp/s2i263248273/upload/src/index.html as src/index.html
I0708 12:22:39.858016   10220 docker.go:722] Removing container "s2i_sti_test_sti_fake_no_tar_83e4f98d" ...
I0708 12:22:39.868368   10220 docker.go:726] Removed container "s2i_sti_test_sti_fake_no_tar_83e4f98d"
I0708 12:22:39.868465   10220 cleanup.go:33] Removing temporary directory /tmp/s2i263248273
I0708 12:22:39.868477   10220 fs.go:158] Removing directory '/tmp/s2i263248273'
I0708 12:22:39.869708   10220 sti.go:578] 
--- FAIL: TestLayeredBuildNoTarNoName (0.71s)
    integration_test.go:316: An error occurred during the build: non-zero (13) exit code from sti_test/sti-fake-no-tar
```

https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_sti/513/consoleFull

no useful message about what failed unfortunately.

**Comment by gabemontero** [comment]
fyi - i see this intermittently with the new k8s/engine-api docker client as well, for whatever that might be worth

**Comment by bparees** [comment]
haven't seen this lately.

**Comment by bparees** [comment]
reopening as we've seen it again, most recently it happened in windows testing:

**Comment by bparees** [comment]
@jim-minter actually now i'm wondering if the new occurrences are specific to the windows setup, looks like maybe we lost connection to the linux docker machine?

```
--- FAIL: TestLayeredBuildNoTarNoName (1.57s)
	integration_test.go:335: An error occurred during the build: write tcp 172.18.11.159:49643->172.18.10.126:2376: wsasend: An established connection was aborted by the software in your host machine.
```

**Comment by jim-minter** [comment]
@bparees agreed.  I'm wondering how on earth to get the information needed to debug whatever is causing this.

**Comment by bparees** [comment]
just failed again here too:
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_s2i_windows/62/console

**Comment by jim-minter** [comment]
It's happened in jenkins runs 15, 51, 59 and 62, always in TestLayeredBuildNoTarNoName.
It's around the repeated tar.go:286 lines that the problem happens - preparation of a tar file and uploading it to the container.  How far it gets varies; in the failure cases the following lines appear to be the error bubbling up the stack.

Hmm.

**Comment by jim-minter** [comment]
In 62 the error was WSAECONNRESET rather than WSAECONNABORTED.

**Comment by jim-minter** [comment]
Ah, I think I see what's going on.

**Comment by bparees** [comment]
it's baaaaaaaack: https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_s2i_windows/209/

**Comment by jim-minter** [comment]
Hello old friend.

In https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_s2i_windows/209/ I think something like the following happened:
win -> lin: send some tar data
lin: run sh, try to run tar, fail, send error message, close file descriptors, exit
win -> lin: keep on sending tar data
lin: send TCP reset

Then, perhaps due to packet loss, reordering or TCP stack implementation (e.g. if receiving a reset shortcuts data in receive buffer on a Windows machine, which is probably feasible), on this occasion the Windows userspace only gets the reset and not the "tar not found" error and the test falls apart.

I haven't managed to recreate this (although I've only tried on my local Linux box) but I think the above fits the logs and the code logic.

Here are some options:
1- accept this is just a bit racey/flakey
2- separate the logic, so we start a separate container first to test for existence of sh and tar (overhead!) or implement some grotty protocol whereby we test for existence of sh and tar, send an ok/fail, and only then start sending tar data if we read an ok
3- remove the missing sh/tar detection logic

@bparees wdyt?

**Comment by bparees** [comment]
lots of bad options :)

if it were day one i'd vote for (3), but alas.

for now i'm going to mark it low priority and go with (1).

**Comment by bparees** [comment]
closing as won't fix (not high enough impact and the fixes are unpalatable)
