### ISSUE TITLE
s2i build /tmp/src

### ISSUE THREAD

**Issue by tmds** [openshift/source-to-image#687]
It looks like the source provided by s2i at /tmp/src is present in the final image.

Is it okay to delete the /tmp/src folder in the assemble script? Would this decrease the image size or will /tmp/src be present anyhow in a layer?

The first step of my assmble script is `cp -Rf /tmp/src/. ./` which is copying over from /tmp/src to the working dir. Is this a meaningful step? Or would it be better to compile the code at /tmp/src directly?

**Comment by bparees** [comment]
> Is it okay to delete the /tmp/src folder in the assemble script? Would this decrease the image size or will /tmp/src be present anyhow in a layer?

yes it's perfectly fine to delete it, in fact we've started shifting our assemble scripts to mv instead of cp the src from /tmp.  It will decrease the image size since all actions of the assemble script occur within a single layer.

> The first step of my assmble script is cp -Rf /tmp/src/. ./ which is copying over from /tmp/src to the working dir. Is this a meaningful step? Or would it be better to compile the code at /tmp/src directly?

if it's a compiled language and you want a minimal sized final application image, compiling in /tmp/src, moving the compiled binary/jar/whatever to the final location from which the application will be run, and then wiping our the source in /tmp/src makes sense.
