### ISSUE TITLE
question : openshift concrete builder resource quota

### ISSUE THREAD

**Issue by guangxuli** [openshift/source-to-image#691]
How the openshift count the resource quota consumed by specific builder image（may be not only one builder image）since it is created by sti builder but not openshift cluster it self (k8s exactly). I knew the quota is equal to the sti builder but how to count if we customized the quota(if can do that), it looks like the cluster can't count the resource((cpu/memory etc) quota consumed by specific builder.
And i also put the question on the [stackoverflow].(http://stackoverflow.com/questions/42366749/openshift-concrete-builder-quota)

**Comment by bparees** [comment]
I'm not quite sure what you're asking.  It sounds like you understand that we constrain the builder image container to the same resource limits that are put on the builder pod (which are the resource limits defined on the build resource), so we ensure that the user is not using more than their resource quota, including resources used by the specific builder container that is launched from within the builder pod.

If you're asking how does openshift know how much resource is actually being consumed by the builder container, since openshift didn't launch/manage the container directly, the answer is "it doesn't".  Which probably means the builder pods are less likely to be targets for eviction since from openshift's perspective, the pod will not be using much resource.  @derekwaynecarr might be able to flesh out the implications in more detail.

**Comment by guangxuli** [comment]
@bparees sorry i am late, thanks so much. I got it.

**Comment by bparees** [comment]
no problem.
