### ISSUE TITLE
Use Incremental Builds with Builder + Runtime Images

### ISSUE THREAD

**Issue by cainj13** [openshift/source-to-image#738]
I'm using a java stack, and would ideally like a builder image where things like my maven configuration and .m2 repository can live without junking up my runtime container.  However, when I try to do an incremental build, I get this:

>  ERROR: Incremental build with runtime image isn't supported

Are there any plans to provide a way to save artifacts and update the builder image as part of the s2i build?

**Comment by bparees** [comment]
at present we aren't planning additions to the extended build feature, but you can get pretty much the same result by running two s2i builds:

1) an s2i build that uses your builder image base, does an incremental build, and produces an image that contains your jar/war.

2) a second s2i build, using the extended mechanism, that uses the first image as your "builder" image, but the build will basically be a no-op since the war/jar already exists in the image.  You can provide a no-op assemble script.
