### ISSUE TITLE
Incremental builds uses the save-artifacts script from the previous image

### ISSUE THREAD

**Issue by willtcarey** [openshift/source-to-image#772]
Today I was trying to develop and debug a save-artifacts script to make incremental builds work the workflow is a little bit cumbersome to do that when the save-artifacts scripts are baked into the image.

As far as I can tell currently, every time you change the save-artifacts script you need to rebuild your docker image and then run the `s2i build` command again with the incremental flag. Except when you do that the build uses the save-artifacts script from the previous image so your changes aren't picked up yet! You actually have to call `s2i build` a second time to test if the change in your save-artifacts script worked correctly.

I've i'm actually missing how something works please correct me!

I would suggest always copying the save-artifacts from the new image to the old image before running it so that you don't have to go through 2 builds to see your changes.

**Comment by bparees** [comment]
you should be able to provide your own save-artifacts script (e.g. the same way you do w/ your assemble or run script), that would be the easiest way to ensure you're always getting the save-artifacts behavior you want/expect.  (That said, i'm actually not 100% certain we handle that correctly, so i'd love to hear back as to whether it works as expected for you).

Copying the save-artifacts script from the new image isn't reliable because there's no guarantee the new save-artifacts script is compatible w/ the old image, so it's not a safe thing to do.  (but if you provide a save-artifacts script yourself, then it's on you as to whether it'll work or not).

**Comment by willtcarey** [comment]
@bparees Ok that makes sense why you wouldn't want to copy the script over. We were developing using scripts built into the image but I can see how using external scripts could improve that, we'll try it!
