### ISSUE TITLE
run multiple exec command

### ISSUE THREAD

**Issue by johnreytanquinco** [openshift/source-to-image#783]
I have an application image and a database(separate container pod). Basically, I was able to successfully connect the app into database using manual steps(running `drush install` command in the container pod). I want that when I deploy the image, `drush install` will also be called in the process.

Now I created a script(`entrypont.sh`) that will connect the app into its database.

My concern is how can I put together, 1-running the apcahe, and 2-connecting app to the db.
Can I just issue multiple `exec` commands in the `s2i/bin/run`?
Like for example:
```
echo "---> Starting apache2..."
exec apache2 FOREGROUND

echo "---> Starting Drupal Installation..."
exec entrypoint FOREGROUND
```

Second thing does `-D` means detach in `exec test -D FOREGROUND`, and `FOREGROUND` means running in foreground? Thanks!

**Comment by bparees** [comment]
> Can I just issue multiple exec commands in the s2i/bin/run?

No, exec replaces the running script with the exec'd process, so that will not work (your 2nd exec would never run unless the first exec terminates).

The right solution to this is probably a post-deployment hook:
https://docs.openshift.org/latest/dev_guide/deployments/deployment_strategies.html#lifecycle-hooks

> Second thing does -D means detach in exec test -D FOREGROUND, and FOREGROUND means running in foreground? Thanks!

-D is an argument to httpd that allows you to pass config parameters, in this case the config parameter is FOREGROUND to ensure httpd runs in the foreground which is what we desire so that the container continues running.

from man httpd:
```
  -D parameter
              Sets a configuration parameter which can be used with <IfDefine>
              sections  in  the  configuration  files to conditionally skip or
              process commands at server startup and restart. Also can be used
              to   set   certain   less-common  startup  parameters  including
              -DNO_DETACH (prevent the parent from forking)  and  -DFOREGROUND
              (prevent the parent from calling setsid() et al).
```

**Comment by bparees** [comment]
Note that you'll want to protect your installation logic with a check that only does it the first time, if your app is already setup you don't want to do it again.

**Comment by johnreytanquinco** [comment]
Thanks you for your response. Will try that out.

**Comment by johnreytanquinco** [comment]
Hi @bparees , that works for me. I modified the deploy config from OpenShift web console and redeploy but how can I add the hook config in the image since this is like a different approach. TIA

**Comment by bparees** [comment]
you don't add the hook config to the image, you define what the hook should do as part of the deploymentconfig.

**Comment by johnreytanquinco** [comment]
Updated my comment.

**Comment by johnreytanquinco** [comment]
>you don't add the hook config to the image, you define what the hook should do as part of the deploymentconfig.
Okay, I understand but my goal is that when I create a new project using the image I push into OpenShift registry, a fresh installed site should be spin up. No more steps be done.

So if we only define the hook in the deployconfig, maybe there is an option to create an init command to include it when building the image that will run 1st - apache, then 2nd - enttrypoint script.

**Comment by magick93** [comment]
@johnreytanquinco - to clarify, you are saying, when using the post deploy hook in the deployment config, OpenShift would spin up a new pod to run the command in. It would not run the command in the primary web pod?

**Comment by bparees** [comment]
If you want the image to spin up self-contained, the deploymenthook won't work since you're always going to require the user to configure the deploymenthook.  One way to handle that is to define an openshift template for your application, and have users instantiate the template.  The template would include the deploymentconfig with the deploymenthook defined.

However if you are determined to have the startup script for the image itself handle the installation steps, you can do one of two things:

option 1:

* run the existing apache step, but instead of running it as an exec, just run it, and background it with &
* run the install steps
* foreground the apache process that was backgrounded

This means your apache process will not get any signals sent to the container, however.

option 2:

do option 1, but also setup `trap` logic in the run script that will trap the signals being sent to the run script, and pass them to the pid for the apache process.

**Comment by johnreytanquinco** [comment]
Hi @bparees , thanks for your suggestions. 
For:
> option 1:

Are the steps will look like this?
```
apache2 &
/var/www/html/entrypoint.sh
exec apache2 -D FOREGROUND
```
Thanks!

**Comment by bparees** [comment]
@johnreytanquinco not quite:

```
apache2 &
/var/www/html/entrypoint.sh # i assume this is doing your other setup work that you want to run
fg %1
```

Again, this is going to leave the container in a state where signals are sent to the shell script, not to the apache process, so things like clean shutdown will not work properly unless you setup the shell script to relay the signals to the apache process.
