### ISSUE TITLE
Custom s2i - separate builder and runner images - how to copy binary?

### ISSUE THREAD

**Issue by magick93** [openshift/source-to-image#797]
Hello

I am working on a custom s2i image. The use-case is, I want to to compile c++ code using a dedicated builder image. Then when the source is compiled, I need to copy the binary artifact to another image, used exclusively for running the application.

I have already created the builder image - and it is compiling the source code.
I have created a separate folder and dockerfile for the runner image. 

My question is, how do I copy the compiled artifact from the builder to the runner?

Thanks

**Comment by bparees** [comment]
are you intending to do this on openshift or in a standalone environment?

**Comment by magick93** [comment]
The intention is to ultimately do this in OpenShift.

But, Im taking it one step at a time. So, standalone, initially, is fine.

**Comment by bparees** [comment]
well if openshift is your target, this is the way to do it:
https://docs.openshift.org/latest/dev_guide/builds/advanced_build_operations.html#dev-guide-chaining-builds

doing it outside openshift is a bit trickier.  There is the "extended build" pattern in s2i which enables this, but we're largely moving away from that.  You could also just use "docker cp" to extract the compiled content from your builder image and then use it as an input to your runtime image (which is close to what a chained build does in openshift).

**Comment by magick93** [comment]
Hi @bparees 

Doing this in OpenShift does look much cleaner - but honestly, Im confused!

I am making some progress! I have a builder image. I am able to pull source from git, into my builder image. The builder image successfully compiles the (cpp) code.



```
apiVersion: v1
kind: BuildConfig
metadata:
  creationTimestamp: '2017-09-01T10:01:16Z'
  name: wine-artifact-build2
  namespace: default
  resourceVersion: '109283'
  selfLink: /oapi/v1/namespaces/default/buildconfigs/wine-artifact-build2
  uid: 7e937df1-8efc-11e7-a50d-002421dde3d7
spec:
  nodeSelector: null
  output:
    to:
      kind: DockerImage
      name: 'myrunner:10.1'
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: /winecpp
    git:
      ref: develop
      uri: 'https://gitlab.com/myco/myrepo.git'

    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: DockerImage
        name: 'myco/mywinebuilder:1.0.0-alpha3'
    type: Source
  triggers: []
status:
  lastVersion: 3
```
Next I want to take the compiled artifact, and using another docker image - a runner image - make a new image, or new tag of the runner image, based on the runner image.

But, when I try the above, I am getting the following error:


Pushing image myrunner:10.1 ...
--
  | error: build error: Failed to push image: API error (500): {"message":"You cannot push a \"root\" repository. Please rename your repository to docker.io/\u003cuser\u003e/\u003crepo\u003e (ex: docker.io/\u003cuser\u003e/myrunner)"}"}

I dont fully understand the concept of ImageStreams yet. I know that my builder and runner images work, so for the meantime am ok with using docker images rather than ImageStreams. But, if its easier to use ImageStreams, then would try this too.

**Comment by bparees** [comment]
it'll be easier for you to use imagestreams, but the key issue you're having right now is that since you are using direct DockerImage references, and you haven't indicated a repository, your images are being pushed to docker.io by default.  That means you are trying to push to "docker.io/myrunner:10.1" which, as the error indicates, is a root repository on docker.io and you're not allowed to push there.

This will definitely work better if you define an imagestream and push to it. Here's an example of how to define a new imagestream:
https://github.com/openshift/origin/blob/master/examples/sample-app/application-template-stibuild.json#L71-L81

and a buildconfig that will push to it, using a tag named "latest":
https://github.com/openshift/origin/blob/master/examples/sample-app/application-template-stibuild.json#L151-L156

Once you have that working, your image will be built+pushed to the openshift registry.

You can then define your second build which uses that same imagestreamtag reference as the "from" image for an image source input, as shown in the sample docs i linked.

**Comment by rezie** [comment]
@bparees Was there a reason why the runtimeImage feature was removed? I realize that it's described as tech preview, but was curious to know if you knew why.

**Comment by bparees** [comment]
@rezie we decided that the chained builds approach in openshift was more flexible and simpler to support than the runtime-image feature in s2i.  (among other things, chained builds allows you to chain a docker+s2i build together, so you can use an s2i build to produce your artifacts and a docker build to layer them into your application image, for example).

https://docs.openshift.org/latest/dev_guide/builds/advanced_build_operations.html#dev-guide-chaining-builds

**Comment by magick93** [comment]
Hello

I have some further questions related to developing a builder and runner s2i project.

**Copying multiple files from builder to runner**
On the docs, at https://docs.openshift.com/container-platform/3.5/dev_guide/builds/advanced_build_operations.html#dev-guide-chaining-builds there is the following example:

```
source:
    dockerfile: |-
      FROM jee-runtime:latest
      COPY ROOT.war /deployments/ROOT.war
    images:
    - from: 
        kind: ImageStreamTag
        name: artifact-image:latest
      paths: 
      - sourcePath: /wildfly/standalone/deployments/ROOT.war
        destinationDir: "."
```
How would I copy several artifacts? For example, I am compiling a cpp application. I need to copy the compiled artifact, plus some shared libs, and also need to install some libs.

**Comment by bparees** [comment]
> How would I copy several artifacts? 

you can have as many paths entries as you want.  the source can also be a directory instead of a specific file.

see more docs here:
https://docs.openshift.org/latest/dev_guide/builds/build_inputs.html#image-source

>  Is it possible to export the clean build configs as yaml?

you can try using "oc export bc/yourbuildconfig" but it may still not be as clean as you want it, getting cleaner exports is something we're working on.  In the meantime, you may still have to clean up the exported object definition a bit yourself.

> How do I tell the builder image stream not to deploy?

don't create a deploymentconfig that's configured to deploy the imagestream.

> What is the correct terminology - when the builder image is building (compiling source from git) is it consider to be building or deployed?

building.

> According to https://docs.openshift.com/enterprise/3.2/creating_images/s2i.html the run script is required. Is this required for the builder image too?

if you're just using an s2i builder image to compile artifacts, but have no intention of actually running the the resulting image directly, the run script should not be needed.  I'm not sure offhand if something will attempt to verify that you have one and fail things if you don't though, if so you may need to supply a dummy run script just to meet the requirement.  It won't be invoked in your scenario, though.

> Do you have any recommendations for doing this locally? Is it possible to use the s2i cli utility when there is both a builder and runner?

Without openshift, the pattern of "extract some content from image1 and layer it into image2" is more difficult to implement today.  You can always use "docker cp" to extract content from an container, so you could do something like:

```
$ s2i build source-repo your_custom_s2i_builder_image output_image # equivalent to the first build in your chain

$ docker create output_image # create a container from your image

$ docker cp container_id:/path/to/artifacts/in/image .  # copy content from image to local filesystem

$ docker build .  # assumes you have a local Dockerfile that will COPY the local content, equivalent to the second build in your chain

$ docker rm container_id # clean up the temporary container you created
```

That's fairly close to what openshift is doing for you when you do a build with inputs from an existing image.
