### ISSUE TITLE
buildah support

### ISSUE THREAD

**Issue by TomasTomecek** [openshift/source-to-image#806]
Hi, are there any plans to support other container runtimes? The one I have in mind is [buildah](https://github.com/projectatomic/buildah).

**Comment by bparees** [comment]
Not at present, we are however considering adding a feature to let you generate a Dockerfile from the s2i invocation and you could then build that dockerfile with whatever runtime you want.

**Comment by TomasTomecek** [comment]
Why would you want to commit to dockerfiles?

**Comment by bparees** [comment]
because for better or worse, dockerfiles are now the standard way to define image shape, regardless of what tool you actually use to construct the image.

**Comment by TomasTomecek** [comment]
That's what worries me: will they be a standard way in one year? Or three years?

**Comment by bparees** [comment]
They'll certainly be *a* standard.  and if something else comes along, we can always add support for producing that too.

**Comment by TomasTomecek** [comment]
okay, sounds reasonable

**Comment by westurner** [comment]
buildah support could enable rootless building.

If `podman-docker` installs `podman` at `/usr/bin/docker`, do the builds build with podman (into the OCI standard `/var/lib/containers` directory) instead of docker?

This article does a great job of justifying podman and buildah e.g. in terms of security advantages:
https://developers.redhat.com/blog/2019/02/21/podman-and-buildah-for-docker-users/

**Comment by westurner** [comment]
AFAIU the `no-cache` and `stop-layering` tags in ansible-bender are not possible with docker, podman, or buildah?
https://github.com/ansible-community/ansible-bender#caching-mechanism

**Comment by TomasTomecek** [comment]
@westurner yes, you would have to script the build process yourself: it's definitely not possible with dockerfiles
