### ISSUE TITLE
Potential improvements to I/O wrt /tmp/artifacts and /tmp/src

### ISSUE THREAD

**Issue by asottile** [openshift/source-to-image#832]
I've been playing a lot with incremental builds recently and trying to optimize some of the time spent in them, here's some of the things I've noticed and potentially some improvements that can be made there:

1. `/tmp/artifacts` and `/tmp/src` are added to the builder, nearly every builder must `rm -rf /tmp/artifacts /tmp/src` as part of `assemble`
    - this is pretty easy to forget and can cause images to balloon
    - not only that, the `rm -rf ...` call can be slow
2. When using `--copy`, the entire source directory is copied to `/tmp/s2i####` and then copied into the container (2 copies)
    - this can be slow for very large source directories
3. When saving artifacts, the intermediate tar representation is untarred into `/tmp/s2i####/artifacts`
    - this can be slow if the tar contains _many many_ small files

For 1. and 2., it seems this could be solved relatively easily by using read-only docker `--volume`s -- though this would be a (potentially difficult?) breaking change:
- builders which currently `rm -rf /tmp/artifacts /tmp/src` would need to stop doing that
- this avoids the overhead of copying those into the container, as well as the overhead from `rm -rf`s
- builders which assume `/tmp/src` / `/tmp/artifacts` should be present in the resulting image would need to adjust (do any do this intentionally? I can't think of a valid usecase)

For 3. I don't have a great solution, I've been double-tarring (tar once, then tar the tar and stream that to stdout) which seems to improve the many-small-files case.

Thoughts on this?  I've tried sketching up some of my ideas in a [quick proof of concept](https://github.com/asottile/minis2i/blob/master/minis2i) but wanted to get some feedback before trying to incorporate some of these ideas.

**Comment by asottile** [comment]
An idea for 3. would be to change the tar protocol to a docker volume:
- create a docker volume
- run `save-artifacts-v2` in an old image, this script now has the responsibility of copying artifacts into `/tmp/artifacts` (the docker volume, mounted `rw`)
- mount the docker volume to `/tmp/artifacts` (`ro`), `assemble` can copy things out of it

**Comment by bparees** [comment]
> /tmp/artifacts and /tmp/src are added to the builder, nearly every builder must rm -rf /tmp/artifacts /tmp/src as part of assemble

they should do a mv to move the artifacts/source to the desired location, not a cp+rm -rf:
https://github.com/sclorg/s2i-python-container/blob/master/3.6/s2i/bin/assemble#L15

> When using --copy, the entire source directory is copied to /tmp/s2i#### and then copied into the container (2 copies) 

obviously the second copy is inevitable.  The first one could potentially be avoided but i believe today we use the /tmp/s2iXXX as a working dir and do some manipulation of the source there, that can't be done on the user's actual source directory since we wouldn't want to mutate that.

> For 1. and 2., it seems this could be solved relatively easily by using read-only docker --volumes -- though this would be a (potentially difficult?) breaking change:

Unfortunately that's not a viable approach within openshift which is the primarily consumer of s2i.  If the performance is truly critical and problematic for you I suppose we'd consider an optional path which allows the source to be injected via a mount instead of via tar, but the bar is going to be pretty high for such a change since it will add a lot of new codepaths.

Doing it as an option would help address the compatibility problem as well.

> builders which assume /tmp/src / /tmp/artifacts should be present in the resulting image would need to adjust (do any do this intentionally? I can't think of a valid usecase)

in some cases this is used to run unit/smoke tests on the application image after it is built.  See: openshift postcommit hook.  But certainly this requirement can be addressed by explicitly copying the source if it's desired.

**Comment by asottile** [comment]
> they should do a mv to move the artifacts/source to the desired location, not a cp+rm -rf:
https://github.com/sclorg/s2i-python-container/blob/master/3.6/s2i/bin/assemble#L15

ah I guess I was assuming more than checking things -- I've been avoiding `mv` here as it pulls in a bunch of unnecessary things that would usually get filtered out by `.dockerignore` / etc.

I'll look into the other things but I don't really want to add to the tangle 😆

**Comment by asottile** [comment]
Seems the primary confusing is I usually like to assume source is immutable during builds whereas s2i allows (encourages?) mutation -- I'll think about this some more :)

**Comment by asottile** [comment]
fwiw, here's a prototype of how `/tmp/artifacts` as a volume (instead of `tar`) might work: https://github.com/asottile/minis2i/pull/1/files

**Comment by burdiyan** [comment]
Point 3 is really a stopper for us to use s2i. Incremental builds with large node_modules folder with many small files is very slow because of streaming those files to the host, and then to the build container.

I was about to post some proposals for improving that and found out this issue. The solution with volumes can really speed up incremental builds and also can bring some other benefits:

- There is no need to stream artifacts with save-artifacts script, maybe needed files can be specified with labels or CLI flags.
- S2I would check if there is any previous builds for this image, create the container of it with docker create command specifying volume mounts for all specified artifacts.
- S2I would run a build container with --volumes-from option mounting artifacts from the previous build volumes into /tmp/artifacts and then copy artifacts to the WORKDIR (this way artifacts remain present in the new built image).
- When build finished, S2I would remove the previous build container and it's volume mounts and newly created builds becomes the last build.

Disk IO should also be significantly less when doing incremental builds this way.

This change can be done in a backward compatible way so that both workflow could work at the same time: for example if save-artifacts scripts is present, run it the old way, otherwise use volumes approach.
