### ISSUE TITLE
No executable permissions on s2i scripts on Windows

### ISSUE THREAD

**Issue by Luladjiev** [openshift/source-to-image#839]
I have the same problem as #620 but when I create an app with minishift on Windows system

```
/usr/bin/container-entrypoint: line 2: /usr/libexec/s2i/usage: Permission denied
/usr/bin/container-entrypoint: line 2: exec: /usr/libexec/s2i/usage: cannot execute: Permission denied
```

Is this a problem in s2i or in minishift?

**Comment by bparees** [comment]
Likely neither.  What s2i builder image are you trying to use?

**Comment by bparees** [comment]
And how did you "create an app"?  This looks like you're just trying to run one of the s2i builder images directly (they default to printing out their usage information) w/o having actually run an s2i build to add your app's source code and produce an application image.

**Comment by Luladjiev** [comment]
The image I use is openshift/base-centos7

this is the Dockerfile

```

FROM openshift/base-centos7

ENV ESPORT_SCHEDULE 1.0

LABEL maintainer="luladjiev@gmail.com" \
      io.k8s.description="Platform for building Spring.io project" \
      io.k8s.display-name="Esport-Schedule builder" \
      io.openshift.expose-services="8080:http"
#      io.openshift.tags="builder,x.y.z,etc."

RUN curl --silent --location https://rpm.nodesource.com/setup_8.x | bash - && \
    yum install -y java-1.8.0-openjdk maven nodejs && \
    yum clean all -y

# TODO (optional): Copy the builder files into /opt/app-root
# COPY ./<builder_folder>/ /opt/app-root/

COPY ./s2i/bin/ /usr/libexec/s2i

RUN chown -R 1001:1001 /opt/app-root

USER 1001

EXPOSE 8080

CMD ["/usr/libexec/s2i/usage"]
```

The steps I made are:
```
docker build -t esport-centos7 .

s2i build . esport-centos7 esport-app

oc new-app https://github.com/lunixgames/esport-schedule -l name=esapp
```

**Comment by Luladjiev** [comment]
If I try

```
docker run -p 8080:8080 esport-app
```

it works as expected

**Comment by bparees** [comment]
> s2i build . esport-centos7 esport-app

this does an s2i build using esport-centos as the s2i builder image.  not surprising it works.

>  oc new-app https://github.com/lunixgames/esport-schedule -l name=esapp

this is going to detect the Dockerfile in your repo and setup a Docker strategy build that effectively does a "docker build ." on your repository.  Since your Dockerfile ends with:

https://github.com/LunixGames/Esport-Schedule/blob/master/Dockerfile#L28

The image it produces is going to try to run that (And apparently it's not marked executable, nor is it what you really want).

What you need to do:

1) push your "esport-centos7" s2i build image to a registry (either the openshift internal one, or 
dockerhub) so that openshift will be able to pull it down during the s2i build process.

2) Tell new-app to use that image as the s2i builder image and to use the s2i strategy to build your repository: `oc new-app --strategy=source someregistry/namespace/esport-centos7~https://github.com/lunixgames/esport-schedule -l name=esapp`

**Comment by Luladjiev** [comment]
Ahh I see, thanks. Closing the issue.
