### ISSUE TITLE
Copied repos duplicate symlinks

### ISSUE THREAD

**Issue by adambkaplan** [openshift/source-to-image#892]
If an s2i build uses the `--copy` instruction and the source has a symlink, the s2i image produces two full copies of the symlinked file.

Reported in https://github.com/openshift/origin/issues/19809

**Comment by bparees** [comment]
@wozniakjan here's one you can take a look at.

**Comment by wozniakjan** [comment]
Currently, the source-to-image doesn't care much about symlinks. Only if they are broken on the `src` file system, it creates the same symlink on `dst` file system. In other cases, it treats non-broken symlinks as regular files, opens `src` file, creates new `dst` file and copies the content. That's why a symlink on `src` turns into a regular file on `dst`

https://github.com/openshift/source-to-image/blob/d1e7db8290f8e8a000a94a503d5bc9babf74d20e/pkg/util/fs/fs.go#L193-L242

There are a couple of scenarios when copying symlinks as symlinks can be tricky
1) `src` has a symlink with relative path `../../../abc` - this is very likely going to be a completely different file on `dst` and symlink can be broken
2) `src` has a symlink with absolute path - will break
3) ( and hardlinks are probably only going to make this harder to solve, pun intended )

**One potential solution I see is to leave it all at the user**
1) add a field, eg. `FollowSymlinks`, with default to `true` here
https://github.com/openshift/source-to-image/blob/012c77ca17bc928632232d407e1e0476b7480f63/pkg/api/types.go#L43-L44
2) when `FollowSymlinks` is `true` - behave as implemented currently
3) when `FollowSymlinks` is `false` - if there is a symlink in `src` filesystem, make a similar symlink in `dst`

**Comment by bparees** [comment]
>  In that sense I'm inclined to keep this code around with your proposed configuration, though I would make the default false. 

i'm not clear if you're suggesting the name of the setting should be changed such that a value of false results in the current behavior, or you're suggesting the default behavior should be to not followsymlinks?

I would be on board w/ the former, if we're going to add an option at all.

Also @adambkaplan is the title for this issue correct?  "Copied repos duplicate symlinks"?  That doesn't sound the same as "copied repos turn symlinks into raw files" (it sounds like you're ending up w/ doubled files)

**Comment by bparees** [comment]
I also think we need to take the usage into account.  We move/copy files around for different reasons. It's possible that in the scenario described in https://github.com/openshift/origin/issues/19809 we should be retaining the file as a symlink, but in the work being done with "--copy" we should not.

**Comment by adambkaplan** [comment]
@bparees updated the title for clarity.

> i'm not clear if you're suggesting the name of the setting should be changed such that a value of false results in the current behavior, or you're suggesting the default behavior should be to not followsymlinks?

I was suggesting the latter, though I wanted your input on this. Perhaps change to `KeepSymlinks` - `false` = current deep copy behavior, `true` = shallow copy as a symlink.

**Comment by bparees** [comment]
> I was suggesting the latter

i'd definitely have concerns about breaking existing behavior.

Adding a flag (such that the value defaults to false and the behavior defaults to the existing behavior) would be ok, but ultimately we'd have to wire it up to the build api so we should be thinking about what that would look like from the start.

Which comes back to my earlier comment:  we copy/move files around for a lot of reasons during a build flow.  are they all impacted by this?  do we want them to all behave the same way or are there reasons why some should behave differently from others?

Is this fundamentally the result of what our tar helper is doing?

**Comment by adambkaplan** [comment]
> we copy/move files around for a lot of reasons during a build flow. are they all impacted by this? do we want them to all behave the same way or are there reasons why some should behave differently from others?

Based on my understanding & analysis, almost all are impacted by this. It's hard for me to find a good use case why we'd need some portion of the build to copy as symlink, and others to deep copy the raw file. Enabling this would also lead to quite a bit of "config clutter".

> Is this fundamentally the result of what our tar helper is doing?

It looks like the tar helper is using the standard `io.Copy` to write files to the tar stream. The symlink deep copy is happening upstream from there (ex: the git clone).
https://github.com/openshift/source-to-image/blob/master/pkg/tar/tar.go#L261

**Comment by wozniakjan** [comment]
> It looks like the tar helper is using the standard io.Copy to write files to the tar stream. The symlink deep copy is happening upstream from there (ex: the git clone).

and also handles symlinks by default
https://github.com/openshift/source-to-image/blob/d2e7686fb703feed3185da07f77aaafb4721459b/pkg/tar/tar.go#L225-L239

It appears to be only `fs.go` that was causing problems

> but ultimately we'd have to wire it up to the build api so we should be thinking about what that would look like from the start.

for testing purposes, I just hardcoded the flag to always keep symlinks https://github.com/wozniakjan/origin/pull/6/files. I can imagine it could make sense as a flag in `BuildConfig`

**Comment by bparees** [comment]
i suspect we did this for s2i cli w/ --copy so that if you were building a local dir w/ a symlink reference outside the working dir, things would just work.  When running a build in openshift it makes less sense (since you don't control the host environment, you wouldn't have symlinks that reference locations outside the source dir).

So i think for s2i cli behavior, we probably want to keep the default behavior (deep copy the symlink) so that links to host files (such as /etc/hosts or something) copy in the expected content.

In openshift i think we would want to change the behavior to retain symlinks as symlinks (the original issue that was reported against openshift), but i don't think we want to introduce it as an option.

so i think your starting point for this fix is valid (make it configurable in s2i behavior, retaining the existing behavior as default) and then when we vendor into origin we'll want to set the option differently to actually resolve the original reported issue(https://github.com/openshift/origin/issues/19809)
