### ISSUE TITLE
there should be a way to gracefully cancel build

### ISSUE THREAD

**Issue by gtema** [openshift/source-to-image#902]
Upon particular logic I want to have possibility to decide, whether new build with s2i is required or not (i.e. changes in git are present, but they are not relevant for the new image to be built). After deciding I can do `exit 0`, but this will still build new container. `exit 1` marks build as failed, which is not the case.
One possibility would be to return the same image (when incremental is invoked).

**Comment by bparees** [comment]
Unfortunately there's no reliable, consistent, and backwards compatible way for the assemble script to report such a desire to s2i.  (we can't pick an arbitrary exit code to indicate "i didn't fail, but don't commit these changes to a new image please" because that code could also be used by other assemble scripts as a legitimate failure code).

If you want this behavior you can consider wrapping your s2i invocation with some shell logic that checks for such a situation by examining the output of the s2i assemble invocation, though.
