### ISSUE TITLE
An error occurred: fork/exec C:\Program Files\Git\cmd\git.exe

### ISSUE THREAD

**Issue by doggy8088** [openshift/source-to-image#917]
I'm using `Microsoft Windows [Version 10.0.17134.228]`.

When I run `s2i build https://github.com/sclorg/nginx-container.git --context-dir=1.12/test/test-app/registry.access.redhat.com/rhscl/nginx-112-rhel7:latest nginx-sample-app` command.  I've got the following error:

```
Submodule 'common' (https://github.com/sclorg/container-common-scripts.git) registered for path 'common'
Cloning into 'C:/Users/user/AppData/Local/Temp/s2i769598283/upload/tmp/common'...
Submodule path 'common': checked out '82aaf71594e2aed8e217b0158a8491d754218065'
Build failed
ERROR: An error occurred: fork/exec C:\Program Files\Git\cmd\git.exe: The directory name is invalid.
```

How to fix this problem?

**Comment by bparees** [comment]
> --context-dir=1.12/test/test-app/registry.access.redhat.com/rhscl/nginx-112-rhel7:latest

your context-dir value does not look valid.  It should be a path that exists within the repository you are building.  Did you forget a space between your context-dir path and the builder image you're trying to pass?

Also since 1.12./test/test-app is a symlink, that might cause problems also..  can you just pass --context-dir=examples/1.12/test-app instead, since that is where the symlink points anyway?
