### ISSUE TITLE
Provide environment variable to the builder to detect incremental builds

### ISSUE THREAD

**Issue by tmds** [openshift/source-to-image#950]
I am adding support for incremental builds to s2i for .NET Core.
The incremental build will pass the 3rd party libraries that are used by an application as artifacts.

Currently the s2i builder is removing those libraries after the build, to reduce size of the application image.

It would be nice if the assemble script could detect when the build is incremental. Then it knows it should keep the libraries for save-artifacts.

Because there is no such mechanism, I'll need to add a builder specific envvar to control removal of the libraries, and the user will need to match that manually with building incremental/not incremental.

**Comment by tmds** [comment]
cc @bparees

**Comment by bparees** [comment]
This is a bit awkward because the build that needs to keep the libraries in the output image, is actually *not* the build that is (necessarily) run as incremental, it's the build before.

The incremental flow is:

1) build imagev1  - whether incremental is true or not, imagev1 obviously must fetch all artifacts
2) build imagev2 - consumes artifacts from imagev1(assuming imagev1 contains artifacts)

So in theory a user can do the following:

1) build(non-incremental) imagev1
2) build(incremental) imagev2 - consumes artifacts from v1

In that scenario, their ideal outcome could be that imagev1 would keep the artifacts (even though when it was built, incremental was set to false), and imagev2 would *not* keep the artifacts (even though incremental was set to true).

Not a huge deal if someone just always sets incremental=true, but something to be aware of before we go down this path.

**Comment by tmds** [comment]
> This is a bit awkward because the build that needs to keep the libraries in the output image, is actually _not_ the build that is (necessarily) run as incremental, it's the build before.

I understand. From command line, you'd have to pass '--incremental' also to the first build.
In OpenShift, you setup the config to incremental, so all builds would be incremental and it is less awkward.

**Comment by tmds** [comment]
Note that the libraries folder for building a typical .NET Core web app takes up 1 GB, which is why we are removing it by default.

**Comment by tmds** [comment]
If this is made available, we'll use it in the .NET Core builder.

**Comment by adambkaplan** [comment]
The s2i binary also as a deprecated `--runtime-image` option, which lets you choose a separate image to use when running -see [here](https://github.com/openshift/source-to-image/blob/master/docs/runtime_image.md). We tend to not advocate this option because it too breaks the incremental build flow.

If your S2I image is deployed on OpenShift, another approach you may consider is a [chained build](https://docs.okd.io/3.11/dev_guide/builds/advanced_build_operations.html#dev-guide-chaining-builds). In this pattern the s2i base always contains dependencies, and developers publish their own "incremental" builds as an ImageStream. Build triggers are then used to take the binaries from the incremental image and place them in a thinner runtime image that is deployed on OpenShift.

**Comment by adambkaplan** [comment]
@tmds @bparees would it make sense to introduce the CLI flag `--save-artifacts`, which acts as an alias to `--incremental`?

**Comment by bparees** [comment]
no i don't think that's the right solution here.

what @tmds needs is a way to say, explicitly, "do not keep dependencies around in the output image, i don't intend to reuse this image in a future incremental build".

--incremental does not indicate that.  --incremental only says "try to reuse artifacts from a previously build" but it is not an indicator as to whether this build should keep artifacts around in the output image.

adding a --save-artifacts flag (or --keep-artifacts) would be ok, but it would have to introduce new behavior, and really all it could do it set the env that @tmds is wanting, so the assemble script can decide whether or not to keep artifacts around.  Which makes it of marginal value since it's dependent on assemble implementers to make use of it.  Arguably you could just use "s2i build --e SAVE_ARTIFACTS=false" (Assuming that was the env var that the assemble script respected) without even introducing anything new in s2i.

The problem is making that a widespread standard, and the fact that it's not quite as obvious/clean as a new flag to s2i.

**Comment by adambkaplan** [comment]
I'd argue for the inverse - `--remove-artifacts` as a CLI flag, which sets an env var (i.e. `S2I_REMOVE_ARTIFACTS`). Up to maintainers to implement this in the assemble script, and for some languages/frameworks this may not be relevant.

**Comment by bparees** [comment]
Sure, that works too. It's still a pretty marginal value add over just passing the env var though.

**Comment by adambkaplan** [comment]
Interpreted languages like JS and Python present their own interesting cases, since the dependencies downloaded may include production libraries and test/development libs. Here's a quick assessment of our s2i images on this front:

1. Ruby
  a. `RACK_ENV` - defaults to "production", if unchanged uses `bundle install --without development:test`
  b. `RAILS_ENV` - if unset, similarly development/test libraries are not downloaded
2. NodeJS - `NODE_ENV` - defaults to "production", test libraries are not downloaded
3. Python - no mechanism in `pip` to do this, [pipenv](https://pipenv.readthedocs.io/en/latest/) does provide support.

**Comment by jmtd** [comment]
Hi there, we basically have the same wish for the OpenJDK containers.
@bparees wrote:
> This is a bit awkward because the build that needs to keep the libraries in the output image, is actually not the build that is (necessarily) run as incremental, it's the build before.
I was under the impression that you needed to specify `--incremental` in both cases. Am I mistaken, or has this changed at some point over the life time of STI/S2I?
