### ISSUE TITLE
Uploading secret (processing tar file) to container failed with invalid symlink (CVE-2018-15664)

### ISSUE THREAD

**Issue by dzianis-shkindzerau** [openshift/source-to-image#987]
Hi,

I am running BuildConfig with s2i strategy on OKD 3.9 cluster and I am getting error:
```
{"message":"Error processing tar file(exit status 1): invalid symlink \"/tmp/..data\" -> \"..2019_08_06_16_00_26.551658995\""}
ERROR: Error occurred during injecting "/var/run/secrets/openshift.io/build/maven-setting" to "/tmp": Error response from daemon:

{"message":"Error processing tar file(exit status 1): invalid symlink \"/tmp/..data\" -> \"..2019_08_06_16_00_26.551658995\""}
```

My BuidConfig is:
```
apiVersion: build.openshift.io/v1
kind: BuildConfig
spec:
  source:
    secrets:
      - destinationDir: /tmp
        secret:
          name: maven-setting
```

Version of Docker daemon on compute node with failed build:
```
 Package version: docker-1.13.1-102.git7f2769b.el7.centos.x86_64
 Go version:      go1.10.3
```

Errors don`t occurs when I roll back docker package version to the older version:
```
Package version: docker-1.13.1-88.git07f3374.el7.centos.x86_64
 Go version:      go1.9.4
```

I found that it is due to this issue:
https://bugzilla.redhat.com/show_bug.cgi?id=1714722

Any plans to fix s2i secrets injection with CVE-2018-15664 fix in docker package?

**Comment by adambkaplan** [comment]
Moving this issue to Bugzilla, as this appears to affect OpenShift builds (and not the s2i tool per se).
Note that this will likely not be patched to OKD 3.9, as it's downstream product (OpenShift Container Platform) reaches end of life in October.

https://bugzilla.redhat.com/show_bug.cgi?id=1738599

**Comment by jbodswor** [comment]
The problem also occurs in Openshift 3.11.  It was introduced after the docker fix https://bugzilla.redhat.com/show_bug.cgi?id=1714722 was applied to fix a vulnerability.  Downgrading to docker 1.13.1-96 or earlier will resolve this issue, however will leave docker vulnerable to the fix that was intended in the bugzilla.

**Comment by gabemontero** [comment]
yep we already know it applied to 3.10 / 3.11 as well @jbodswor but thanks

So the changes in the docker CVE fix, in particular https://github.com/moby/moby/pull/39292/files#diff-7d8fc0dcb0916621d523276add8210c2R33-R44, appear to have some bearing on the symlinks k8s employs with secrets to get automatic updates in case the secret changes, a la:

lrwxrwxrwx. 1 root 1000060000  31 Aug 15 14:59 ..data -> ..2019_08_15_14_59_51.598105595

the relative path is the secret sauce there ... i.e. https://unix.stackexchange.com/questions/390844/creating-a-copy-of-a-file-that-gets-automatically-updated or https://serverfault.com/questions/389997/how-to-override-update-a-symlink

But it looks like the docker CVE fix does not like that use of `..` .... I have some more verifications to do to prove that.

Certainly how k8s mounts secrets into a pod (in this case the build pod) is not going to change.

So we are exploring if we can we work around this .... i.e. convert the symlink to point to an absolute path instead of a relative path, when you are tarring/untarring the content

If we figure it out we'll be updating https://bugzilla.redhat.com/show_bug.cgi?id=1738599 and not this issue.
