### ISSUE TITLE
Environment variable only during build process

### ISSUE THREAD

**Issue by psinger** [openshift/source-to-image#998]
Is there a way to specify environment variables only for the build process? Currently, all variables I specify e.g., in the environment file are also available during the run of the image.

**Comment by bparees** [comment]
Unfortunately that is not currently possible due to the nature of how s2i functions.

It launches a container to run your assemble script, so that container has all the build envs set (so the assemble script can use them).

Once the assemble script completes, the state of the container is committed as the new application image, so there's no way *not* to have the env vars present in that committed app image.

If you use the new "--as-dockerfile" flow in which instead of producing an image, s2i just produces a dockerfile that you can then docker build yourself, you could potentially manipulate the dockerfile before executing it to change env var configurations, but at that point you're getting close to where you're probably better off just hand-rolling your own dockerfiles.
